//! Reader for the differential-testing fixtures `tools/dump_fixtures.py`
//! writes (DESIGN.md "How correctness is established").
//!
//! Dependency-free by construction: DESIGN.md rule 2 only forbids a
//! `[dependencies]` entry (`serde_json` would be fine in
//! `[dev-dependencies]`, which this file lives behind in spirit even though
//! it is not literally gated that way -- see the note in the port report for
//! why a hand-rolled reader was chosen anyway). The fixture files are
//! machine-generated by one producer (`tools/dump_fixtures.py`) with a fixed,
//! simple shape, so a full JSON implementation is not needed: this handles
//! everything `json.dumps` can produce, and nothing it cannot.
//!
//! Layout: a private `json` submodule is a minimal JSON value parser; the
//! rest of this file maps that generic `Json` tree onto the fixture schema
//! and, for moves, onto [`Move`]. `parse_move` is deliberately the ONE place
//! in the whole crate that maps a move tag string to a `Move` variant --
//! DESIGN.md's rule against a fact living in two registries applies to this
//! mapping as much as it does to card data.

use std::fmt;
use std::path::{Path, PathBuf};

use crate::cards::CardId;
use crate::moves::{ChurchillChoice, Move, PactSide};

// ============================================================ json ======

/// A parsed JSON value. Objects keep insertion order (a `Vec` of pairs, not a
/// map) because nothing here needs key lookup to be fast -- these files are
/// read once, by a test, not on a hot path -- and because that is also
/// simpler than pulling in a hasher.
#[derive(Debug, Clone, PartialEq)]
pub enum Json {
    Null,
    Bool(bool),
    /// All JSON numbers, integer or not. `serde_json` would keep an int/float
    /// split; this reader doesn't need it, since every numeric field here
    /// (seeds, plies, slots, card ages) is small enough to round-trip exactly
    /// through `f64`.
    Num(f64),
    Str(String),
    Arr(Vec<Json>),
    Obj(Vec<(String, Json)>),
}

impl Json {
    pub fn get(&self, key: &str) -> Option<&Json> {
        match self {
            Json::Obj(fields) => fields.iter().find(|(k, _)| k == key).map(|(_, v)| v),
            _ => None,
        }
    }

    pub fn as_str(&self) -> Option<&str> {
        match self {
            Json::Str(s) => Some(s),
            _ => None,
        }
    }

    pub fn as_f64(&self) -> Option<f64> {
        match self {
            Json::Num(n) => Some(*n),
            _ => None,
        }
    }

    pub fn as_bool(&self) -> Option<bool> {
        match self {
            Json::Bool(b) => Some(*b),
            _ => None,
        }
    }

    pub fn as_arr(&self) -> Option<&[Json]> {
        match self {
            Json::Arr(a) => Some(a),
            _ => None,
        }
    }
}

#[derive(Debug)]
struct JsonError {
    pos: usize,
    msg: String,
}

struct JsonParser<'a> {
    s: &'a [u8],
    pos: usize,
}

impl<'a> JsonParser<'a> {
    fn new(s: &'a str) -> Self {
        JsonParser { s: s.as_bytes(), pos: 0 }
    }

    fn err(&self, msg: impl Into<String>) -> JsonError {
        JsonError { pos: self.pos, msg: msg.into() }
    }

    fn peek(&self) -> Option<u8> {
        self.s.get(self.pos).copied()
    }

    fn bump(&mut self) -> Option<u8> {
        let c = self.peek();
        if c.is_some() {
            self.pos += 1;
        }
        c
    }

    fn skip_ws(&mut self) {
        while matches!(self.peek(), Some(b' ' | b'\t' | b'\n' | b'\r')) {
            self.pos += 1;
        }
    }

    fn expect(&mut self, b: u8) -> Result<(), JsonError> {
        if self.peek() == Some(b) {
            self.pos += 1;
            Ok(())
        } else {
            Err(self.err(format!("expected {:?}", b as char)))
        }
    }

    fn literal(&mut self, lit: &str, val: Json) -> Result<Json, JsonError> {
        let end = self.pos + lit.len();
        if self.s.get(self.pos..end) == Some(lit.as_bytes()) {
            self.pos = end;
            Ok(val)
        } else {
            Err(self.err(format!("expected {lit:?}")))
        }
    }

    fn parse_value(&mut self) -> Result<Json, JsonError> {
        self.skip_ws();
        match self.peek() {
            Some(b'{') => self.parse_object(),
            Some(b'[') => self.parse_array(),
            Some(b'"') => self.parse_string().map(Json::Str),
            Some(b't') => self.literal("true", Json::Bool(true)),
            Some(b'f') => self.literal("false", Json::Bool(false)),
            Some(b'n') => self.literal("null", Json::Null),
            Some(c) if c == b'-' || c.is_ascii_digit() => self.parse_number(),
            Some(c) => Err(self.err(format!("unexpected byte {:?}", c as char))),
            None => Err(self.err("unexpected end of input")),
        }
    }

    fn parse_object(&mut self) -> Result<Json, JsonError> {
        self.expect(b'{')?;
        let mut fields = Vec::new();
        self.skip_ws();
        if self.peek() == Some(b'}') {
            self.pos += 1;
            return Ok(Json::Obj(fields));
        }
        loop {
            self.skip_ws();
            let key = self.parse_string()?;
            self.skip_ws();
            self.expect(b':')?;
            let val = self.parse_value()?;
            fields.push((key, val));
            self.skip_ws();
            match self.bump() {
                Some(b',') => continue,
                Some(b'}') => break,
                _ => return Err(self.err("expected ',' or '}' in object")),
            }
        }
        Ok(Json::Obj(fields))
    }

    fn parse_array(&mut self) -> Result<Json, JsonError> {
        self.expect(b'[')?;
        let mut items = Vec::new();
        self.skip_ws();
        if self.peek() == Some(b']') {
            self.pos += 1;
            return Ok(Json::Arr(items));
        }
        loop {
            let val = self.parse_value()?;
            items.push(val);
            self.skip_ws();
            match self.bump() {
                Some(b',') => continue,
                Some(b']') => break,
                _ => return Err(self.err("expected ',' or ']' in array")),
            }
        }
        Ok(Json::Arr(items))
    }

    fn parse_string(&mut self) -> Result<String, JsonError> {
        self.expect(b'"')?;
        let mut out = String::new();
        loop {
            match self.bump() {
                None => return Err(self.err("unterminated string")),
                Some(b'"') => return Ok(out),
                Some(b'\\') => match self.bump() {
                    Some(b'"') => out.push('"'),
                    Some(b'\\') => out.push('\\'),
                    Some(b'/') => out.push('/'),
                    Some(b'b') => out.push('\u{0008}'),
                    Some(b'f') => out.push('\u{000C}'),
                    Some(b'n') => out.push('\n'),
                    Some(b'r') => out.push('\r'),
                    Some(b't') => out.push('\t'),
                    Some(b'u') => {
                        let cp = self.hex4()?;
                        // No surrogate-pair handling: nothing in this
                        // dataset (card names, English prose) needs it, and
                        // the fixture producer never emits one.
                        out.push(char::from_u32(cp as u32).unwrap_or('\u{FFFD}'));
                    }
                    _ => return Err(self.err("bad escape")),
                },
                Some(b) => {
                    // Reinterpret the remaining UTF-8 bytes of this codepoint
                    // directly from the source rather than decoding by hand.
                    let start = self.pos - 1;
                    let width = utf8_width(b);
                    let end = start + width;
                    let bytes = self.s.get(start..end).ok_or_else(|| self.err("truncated utf8"))?;
                    let s = std::str::from_utf8(bytes).map_err(|_| self.err("invalid utf8"))?;
                    out.push_str(s);
                    self.pos = end;
                }
            }
        }
    }

    fn hex4(&mut self) -> Result<u16, JsonError> {
        let mut v: u16 = 0;
        for _ in 0..4 {
            let c = self.bump().ok_or_else(|| self.err("truncated \\u escape"))?;
            let d = (c as char).to_digit(16).ok_or_else(|| self.err("bad hex digit"))?;
            v = v * 16 + d as u16;
        }
        Ok(v)
    }

    fn parse_number(&mut self) -> Result<Json, JsonError> {
        let start = self.pos;
        if self.peek() == Some(b'-') {
            self.pos += 1;
        }
        while matches!(self.peek(), Some(c) if c.is_ascii_digit()) {
            self.pos += 1;
        }
        if self.peek() == Some(b'.') {
            self.pos += 1;
            while matches!(self.peek(), Some(c) if c.is_ascii_digit()) {
                self.pos += 1;
            }
        }
        if matches!(self.peek(), Some(b'e' | b'E')) {
            self.pos += 1;
            if matches!(self.peek(), Some(b'+' | b'-')) {
                self.pos += 1;
            }
            while matches!(self.peek(), Some(c) if c.is_ascii_digit()) {
                self.pos += 1;
            }
        }
        let text = std::str::from_utf8(&self.s[start..self.pos]).unwrap();
        text.parse::<f64>().map(Json::Num).map_err(|_| self.err("bad number"))
    }
}

fn utf8_width(first_byte: u8) -> usize {
    if first_byte & 0x80 == 0 {
        1
    } else if first_byte & 0xE0 == 0xC0 {
        2
    } else if first_byte & 0xF0 == 0xE0 {
        3
    } else {
        4
    }
}

fn parse_json(s: &str) -> Result<Json, JsonError> {
    let mut p = JsonParser::new(s);
    let v = p.parse_value()?;
    p.skip_ws();
    if p.pos != p.s.len() {
        return Err(p.err("trailing data after JSON value"));
    }
    Ok(v)
}

// ======================================================== fixture types ==

/// The first line of a fixture file.
#[derive(Debug, Clone)]
pub struct Header {
    pub players: u8,
    pub seed: i64,
    pub bot: String,
    pub state_every: i64,
    pub max_plies: i64,
    pub engine_rev: Option<String>,
}

/// One decision: the legal-move list and the move chosen from it, plus the
/// digest (and, on some plies, the full state) of what applying it produced.
#[derive(Debug, Clone)]
pub struct Ply {
    pub ply: u32,
    pub decider: u8,
    pub phase: String,
    pub legal: Vec<Move>,
    pub chosen: Move,
    pub digest: String,
    /// `GameState.to_dict()` after `chosen` was applied, present only every
    /// `state_every` plies (always on the last ply of the file). Kept as raw
    /// `Json` rather than a typed `GameState` -- there is no `actions.rs` to
    /// replay into yet, and no `GameState::from_json` either; that conversion
    /// is exactly the "state-replay assertions" `differential.rs` marks
    /// `#[ignore]` until the module bodies land.
    pub state: Option<Json>,
}

/// The last line of a fixture file.
#[derive(Debug, Clone)]
pub struct Footer {
    pub plies: u32,
    pub game_over: bool,
    pub truncated: bool,
}

#[derive(Debug, Clone)]
pub enum Record {
    Header(Header),
    Ply(Ply),
    Footer(Footer),
}

#[derive(Debug)]
pub struct FixtureError {
    pub message: String,
    pub file: Option<PathBuf>,
    pub line: Option<usize>,
}

impl FixtureError {
    fn new(msg: impl Into<String>) -> Self {
        FixtureError { message: msg.into(), file: None, line: None }
    }

    fn with_context(mut self, path: &Path, line: usize) -> Self {
        self.file = Some(path.to_path_buf());
        self.line = Some(line);
        self
    }
}

impl fmt::Display for FixtureError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match (&self.file, self.line) {
            (Some(p), Some(l)) => write!(f, "{}:{l}: {}", p.display(), self.message),
            _ => write!(f, "{}", self.message),
        }
    }
}

impl std::error::Error for FixtureError {}

impl From<JsonError> for FixtureError {
    fn from(e: JsonError) -> Self {
        FixtureError::new(format!("json parse error at byte {}: {}", e.pos, e.msg))
    }
}

fn req<'a>(v: &'a Json, key: &str) -> Result<&'a Json, FixtureError> {
    v.get(key).ok_or_else(|| FixtureError::new(format!("missing field {key:?}")))
}

fn req_str(v: &Json, key: &str) -> Result<String, FixtureError> {
    req(v, key)?
        .as_str()
        .map(str::to_owned)
        .ok_or_else(|| FixtureError::new(format!("field {key:?} is not a string")))
}

fn req_num(v: &Json, key: &str) -> Result<f64, FixtureError> {
    req(v, key)?
        .as_f64()
        .ok_or_else(|| FixtureError::new(format!("field {key:?} is not a number")))
}

fn req_bool(v: &Json, key: &str) -> Result<bool, FixtureError> {
    req(v, key)?
        .as_bool()
        .ok_or_else(|| FixtureError::new(format!("field {key:?} is not a bool")))
}

fn opt_str(v: &Json, key: &str) -> Option<String> {
    match v.get(key) {
        Some(Json::Str(s)) => Some(s.clone()),
        _ => None,
    }
}

// ------------------------------------------------------- move mapping ----

fn move_card(arr: &[Json], tag: &str, idx: usize) -> Result<CardId, FixtureError> {
    let name = arr
        .get(idx)
        .and_then(Json::as_str)
        .ok_or_else(|| FixtureError::new(format!("{tag}: missing card name at index {idx}")))?;
    CardId::by_name(name).ok_or_else(|| {
        FixtureError::new(format!("{tag}: card {name:?} has no CardId -- type layer is incomplete"))
    })
}

fn move_u8(arr: &[Json], tag: &str, idx: usize) -> Result<u8, FixtureError> {
    let n = arr
        .get(idx)
        .and_then(Json::as_f64)
        .ok_or_else(|| FixtureError::new(format!("{tag}: missing number at index {idx}")))?;
    Ok(n as u8)
}

fn pact_side(arr: &[Json], tag: &str) -> Result<PactSide, FixtureError> {
    match arr.get(3).and_then(Json::as_str) {
        Some("A") => Ok(PactSide::A),
        Some("B") => Ok(PactSide::B),
        Some("") => Ok(PactSide::Unspecified),
        other => Err(FixtureError::new(format!("{tag}: bad pact side {other:?}"))),
    }
}

fn churchill_choice(arr: &[Json], tag: &str) -> Result<ChurchillChoice, FixtureError> {
    match arr.get(1).and_then(Json::as_str) {
        Some("culture") => Ok(ChurchillChoice::Culture),
        Some("military") => Ok(ChurchillChoice::Military),
        other => Err(FixtureError::new(format!("{tag}: bad churchill choice {other:?}"))),
    }
}

/// Parse one `["tag", ...]` JSON array into a [`Move`].
///
/// This is the ONE place in the crate that maps a Python move tag string to
/// a `Move` variant -- see `moves.rs`'s own docstring, which promises the
/// variant list is derived from every move tuple the Python engine
/// constructs. This function is the inverse of that promise, checked here
/// against real games rather than against a manual reading of
/// `engine/actions.py` and `engine/interact.py`. An unmapped tag or a card
/// name with no `CardId` is exactly the finding this whole harness exists to
/// surface, so both fail loudly here rather than silently coercing to
/// something plausible.
pub fn parse_move(v: &Json) -> Result<Move, FixtureError> {
    let arr = v
        .as_arr()
        .ok_or_else(|| FixtureError::new("move is not a JSON array"))?;
    let tag = arr
        .first()
        .and_then(Json::as_str)
        .ok_or_else(|| FixtureError::new("move array has no tag string at index 0"))?;
    Ok(match tag {
        "take" => Move::Take { slot: move_u8(arr, tag, 1)? },
        "build" => Move::Build { card: move_card(arr, tag, 1)? },
        "develop" => Move::Develop { card: move_card(arr, tag, 1)? },
        "upgrade" => Move::Upgrade { from: move_card(arr, tag, 1)?, to: move_card(arr, tag, 2)? },
        "wonder_step" => Move::WonderStep { steps: move_u8(arr, tag, 1)? },
        "pop" => Move::Pop,
        "pop_free" => Move::PopFree,
        "revolution" => Move::Revolution { card: move_card(arr, tag, 1)? },
        "play_leader" => Move::PlayLeader { card: move_card(arr, tag, 1)? },
        "play_action" => Move::PlayAction { card: move_card(arr, tag, 1)? },
        "destroy" => Move::Destroy { card: move_card(arr, tag, 1)? },
        "play_tactic" => Move::PlayTactic { card: move_card(arr, tag, 1)? },
        "copy_tactic" => Move::CopyTactic { card: move_card(arr, tag, 1)? },
        "aggression" => Move::Aggression { card: move_card(arr, tag, 1)?, target: move_u8(arr, tag, 2)? },
        "war" => Move::War { card: move_card(arr, tag, 1)?, target: move_u8(arr, tag, 2)? },
        "offer_pact" => Move::OfferPact {
            card: move_card(arr, tag, 1)?,
            target: move_u8(arr, tag, 2)?,
            side: pact_side(arr, tag)?,
        },
        "cancel_pact" => Move::CancelPact { owner: move_u8(arr, tag, 1)? },
        "prepare_event" => Move::PrepareEvent { card: move_card(arr, tag, 1)? },
        "bid" => Move::Bid { n: move_u8(arr, tag, 1)? },
        "bid_pass" => Move::BidPass,
        "defend" => Move::Defend { card: move_card(arr, tag, 1)? },
        "defend_done" => Move::DefendDone,
        "send_unit" => Move::SendUnit { card: move_card(arr, tag, 1)? },
        "send_bonus" => Move::SendBonus { card: move_card(arr, tag, 1)? },
        "send_done" => Move::SendDone,
        "choose" => Move::Choose { n: move_u8(arr, tag, 1)? },
        "churchill" => Move::Churchill { choice: churchill_choice(arr, tag)? },
        "end_turn" => Move::EndTurn,
        "pol_pass" => Move::PolPass,
        "resign" => Move::Resign,
        other => {
            return Err(FixtureError::new(format!(
                "unknown move tag {other:?} -- Move enum in moves.rs has no matching variant"
            )))
        }
    })
}

// -------------------------------------------------------- record parsing -

fn parse_header(v: &Json) -> Result<Header, FixtureError> {
    Ok(Header {
        players: req_num(v, "players")? as u8,
        seed: req_num(v, "seed")? as i64,
        bot: req_str(v, "bot")?,
        state_every: req_num(v, "state_every")? as i64,
        max_plies: req_num(v, "max_plies")? as i64,
        engine_rev: opt_str(v, "engine_rev"),
    })
}

fn parse_ply(v: &Json) -> Result<Ply, FixtureError> {
    let legal_arr = req(v, "legal")?
        .as_arr()
        .ok_or_else(|| FixtureError::new("\"legal\" is not an array"))?;
    let mut legal = Vec::with_capacity(legal_arr.len());
    for (i, mv) in legal_arr.iter().enumerate() {
        legal.push(parse_move(mv).map_err(|e| {
            FixtureError::new(format!("legal[{i}]: {}", e.message))
        })?);
    }
    let chosen = parse_move(req(v, "chosen")?)
        .map_err(|e| FixtureError::new(format!("chosen: {}", e.message)))?;
    Ok(Ply {
        ply: req_num(v, "ply")? as u32,
        decider: req_num(v, "decider")? as u8,
        phase: req_str(v, "phase")?,
        legal,
        chosen,
        digest: req_str(v, "digest")?,
        state: v.get("state").cloned(),
    })
}

fn parse_footer(v: &Json) -> Result<Footer, FixtureError> {
    Ok(Footer {
        plies: req_num(v, "plies")? as u32,
        game_over: req_bool(v, "game_over")?,
        truncated: req_bool(v, "truncated")?,
    })
}

/// Parse one JSON-Lines record (one line of a fixture file).
pub fn parse_record(line: &str) -> Result<Record, FixtureError> {
    let v = parse_json(line)?;
    let kind = req_str(&v, "kind")?;
    match kind.as_str() {
        "header" => Ok(Record::Header(parse_header(&v)?)),
        "ply" => Ok(Record::Ply(parse_ply(&v)?)),
        "footer" => Ok(Record::Footer(parse_footer(&v)?)),
        other => Err(FixtureError::new(format!("unknown record kind {other:?}"))),
    }
}

/// Read and parse a whole fixture file, in line order.
pub fn read_fixture_file(path: &Path) -> Result<Vec<Record>, FixtureError> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| FixtureError::new(format!("{}: {e}", path.display())))?;
    let mut out = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let rec = parse_record(line).map_err(|e| e.with_context(path, i + 1))?;
        out.push(rec);
    }
    Ok(out)
}

/// Every `*.jsonl` fixture file directly inside `dir`, sorted by filename so
/// a test run is deterministic regardless of directory-listing order.
pub fn fixture_files(dir: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|e| e == "jsonl").unwrap_or(false))
        .collect();
    files.sort();
    Ok(files)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn json_round_trips_the_shapes_fixtures_use() {
        let v = parse_json(r#"{"a": 1, "b": [1, 2.5, -3e2, true, false, null, "x\ny\"z"], "c": {}}"#)
            .unwrap();
        assert_eq!(v.get("a").unwrap().as_f64(), Some(1.0));
        let b = v.get("b").unwrap().as_arr().unwrap();
        assert_eq!(b[0].as_f64(), Some(1.0));
        assert_eq!(b[1].as_f64(), Some(2.5));
        assert_eq!(b[2].as_f64(), Some(-300.0));
        assert_eq!(b[3].as_bool(), Some(true));
        assert_eq!(b[4].as_bool(), Some(false));
        assert_eq!(b[5], Json::Null);
        assert_eq!(b[6].as_str(), Some("x\ny\"z"));
    }

    #[test]
    fn parse_move_maps_every_known_tag() {
        let take = parse_json(r#"["take", 3]"#).unwrap();
        assert_eq!(parse_move(&take).unwrap(), Move::Take { slot: 3 });

        let end_turn = parse_json(r#"["end_turn"]"#).unwrap();
        assert_eq!(parse_move(&end_turn).unwrap(), Move::EndTurn);

        let bronze = CardId::by_name("Bronze").expect("Bronze must exist for this test to mean anything");
        let iron = CardId::by_name("Iron").expect("Iron must exist for this test to mean anything");
        let up = parse_json(r#"["upgrade", "Bronze", "Iron"]"#).unwrap();
        assert_eq!(parse_move(&up).unwrap(), Move::Upgrade { from: bronze, to: iron });
    }

    #[test]
    fn parse_move_rejects_unknown_tag() {
        let v = parse_json(r#"["not_a_real_move", 1]"#).unwrap();
        assert!(parse_move(&v).is_err());
    }

    #[test]
    fn parse_move_rejects_unknown_card() {
        let v = parse_json(r#"["build", "Not A Real Card"]"#).unwrap();
        assert!(parse_move(&v).is_err());
    }
}
