//! Reader for the differential-testing fixtures `tools/dump_fixtures.py`
//! writes (DESIGN.md "How correctness is established").
//!
//! Dependency-free by construction: DESIGN.md rule 2 only forbids a
//! `[dependencies]` entry (`serde_json` would be fine in
//! `[dev-dependencies]`, which this file lives behind in spirit even though
//! it is not literally gated that way -- see the note in the port report for
//! why a hand-rolled reader was chosen anyway). The fixture files are
//! machine-generated by one producer (`tools/dump_fixtures.py`) with a fixed,
//! simple shape, so a full JSON implementation is not needed: this handles
//! everything `json.dumps` can produce, and nothing it cannot.
//!
//! Layout: a private `json` submodule is a minimal JSON value parser; the
//! rest of this file maps that generic `Json` tree onto the fixture schema
//! and, for moves, onto [`Move`]. `parse_move` is deliberately the ONE place
//! in the whole crate that maps a move tag string to a `Move` variant --
//! DESIGN.md's rule against a fact living in two registries applies to this
//! mapping as much as it does to card data.

use std::fmt;
use std::path::{Path, PathBuf};

use crate::cards::{Age, CardId, CardType};
use crate::moves::{ChurchillChoice, Move, PactSide};
use crate::state::{
    Auction, CardGains, CardList, Choice, ChoiceKind, ChoiceOption, Colonize, Defense,
    FreeBuildSpec, GainOption, GainOptions, GameState, Keyword, OneTimeDiscount, OptionList, Pact,
    PactList, Pending,
    PendingStack, Phase, PlayerState, Queue, QueueItem, Tableau, TechSlot, MAX_DECK, MAX_PLAYERS,
    ROW_SIZE,
};

// ============================================================ json ======

/// A parsed JSON value. Objects keep insertion order (a `Vec` of pairs, not a
/// map) because nothing here needs key lookup to be fast -- these files are
/// read once, by a test, not on a hot path -- and because that is also
/// simpler than pulling in a hasher.
#[derive(Debug, Clone, PartialEq)]
pub enum Json {
    Null,
    Bool(bool),
    /// All JSON numbers, integer or not. `serde_json` would keep an int/float
    /// split; this reader doesn't need it, since every numeric field here
    /// (seeds, plies, slots, card ages) is small enough to round-trip exactly
    /// through `f64`.
    Num(f64),
    Str(String),
    Arr(Vec<Json>),
    Obj(Vec<(String, Json)>),
}

impl Json {
    pub fn get(&self, key: &str) -> Option<&Json> {
        match self {
            Json::Obj(fields) => fields.iter().find(|(k, _)| k == key).map(|(_, v)| v),
            _ => None,
        }
    }

    pub fn as_str(&self) -> Option<&str> {
        match self {
            Json::Str(s) => Some(s),
            _ => None,
        }
    }

    pub fn as_f64(&self) -> Option<f64> {
        match self {
            Json::Num(n) => Some(*n),
            _ => None,
        }
    }

    pub fn as_bool(&self) -> Option<bool> {
        match self {
            Json::Bool(b) => Some(*b),
            _ => None,
        }
    }

    pub fn as_arr(&self) -> Option<&[Json]> {
        match self {
            Json::Arr(a) => Some(a),
            _ => None,
        }
    }
}

#[derive(Debug)]
struct JsonError {
    pos: usize,
    msg: String,
}

struct JsonParser<'a> {
    s: &'a [u8],
    pos: usize,
}

impl<'a> JsonParser<'a> {
    fn new(s: &'a str) -> Self {
        JsonParser { s: s.as_bytes(), pos: 0 }
    }

    fn err(&self, msg: impl Into<String>) -> JsonError {
        JsonError { pos: self.pos, msg: msg.into() }
    }

    fn peek(&self) -> Option<u8> {
        self.s.get(self.pos).copied()
    }

    fn bump(&mut self) -> Option<u8> {
        let c = self.peek();
        if c.is_some() {
            self.pos += 1;
        }
        c
    }

    fn skip_ws(&mut self) {
        while matches!(self.peek(), Some(b' ' | b'\t' | b'\n' | b'\r')) {
            self.pos += 1;
        }
    }

    fn expect(&mut self, b: u8) -> Result<(), JsonError> {
        if self.peek() == Some(b) {
            self.pos += 1;
            Ok(())
        } else {
            Err(self.err(format!("expected {:?}", b as char)))
        }
    }

    fn literal(&mut self, lit: &str, val: Json) -> Result<Json, JsonError> {
        let end = self.pos + lit.len();
        if self.s.get(self.pos..end) == Some(lit.as_bytes()) {
            self.pos = end;
            Ok(val)
        } else {
            Err(self.err(format!("expected {lit:?}")))
        }
    }

    fn parse_value(&mut self) -> Result<Json, JsonError> {
        self.skip_ws();
        match self.peek() {
            Some(b'{') => self.parse_object(),
            Some(b'[') => self.parse_array(),
            Some(b'"') => self.parse_string().map(Json::Str),
            Some(b't') => self.literal("true", Json::Bool(true)),
            Some(b'f') => self.literal("false", Json::Bool(false)),
            Some(b'n') => self.literal("null", Json::Null),
            Some(c) if c == b'-' || c.is_ascii_digit() => self.parse_number(),
            Some(c) => Err(self.err(format!("unexpected byte {:?}", c as char))),
            None => Err(self.err("unexpected end of input")),
        }
    }

    fn parse_object(&mut self) -> Result<Json, JsonError> {
        self.expect(b'{')?;
        let mut fields = Vec::new();
        self.skip_ws();
        if self.peek() == Some(b'}') {
            self.pos += 1;
            return Ok(Json::Obj(fields));
        }
        loop {
            self.skip_ws();
            let key = self.parse_string()?;
            self.skip_ws();
            self.expect(b':')?;
            let val = self.parse_value()?;
            fields.push((key, val));
            self.skip_ws();
            match self.bump() {
                Some(b',') => continue,
                Some(b'}') => break,
                _ => return Err(self.err("expected ',' or '}' in object")),
            }
        }
        Ok(Json::Obj(fields))
    }

    fn parse_array(&mut self) -> Result<Json, JsonError> {
        self.expect(b'[')?;
        let mut items = Vec::new();
        self.skip_ws();
        if self.peek() == Some(b']') {
            self.pos += 1;
            return Ok(Json::Arr(items));
        }
        loop {
            let val = self.parse_value()?;
            items.push(val);
            self.skip_ws();
            match self.bump() {
                Some(b',') => continue,
                Some(b']') => break,
                _ => return Err(self.err("expected ',' or ']' in array")),
            }
        }
        Ok(Json::Arr(items))
    }

    fn parse_string(&mut self) -> Result<String, JsonError> {
        self.expect(b'"')?;
        let mut out = String::new();
        loop {
            match self.bump() {
                None => return Err(self.err("unterminated string")),
                Some(b'"') => return Ok(out),
                Some(b'\\') => match self.bump() {
                    Some(b'"') => out.push('"'),
                    Some(b'\\') => out.push('\\'),
                    Some(b'/') => out.push('/'),
                    Some(b'b') => out.push('\u{0008}'),
                    Some(b'f') => out.push('\u{000C}'),
                    Some(b'n') => out.push('\n'),
                    Some(b'r') => out.push('\r'),
                    Some(b't') => out.push('\t'),
                    Some(b'u') => {
                        let cp = self.hex4()?;
                        // No surrogate-pair handling: nothing in this
                        // dataset (card names, English prose) needs it, and
                        // the fixture producer never emits one.
                        out.push(char::from_u32(cp as u32).unwrap_or('\u{FFFD}'));
                    }
                    _ => return Err(self.err("bad escape")),
                },
                Some(b) => {
                    // Reinterpret the remaining UTF-8 bytes of this codepoint
                    // directly from the source rather than decoding by hand.
                    let start = self.pos - 1;
                    let width = utf8_width(b);
                    let end = start + width;
                    let bytes = self.s.get(start..end).ok_or_else(|| self.err("truncated utf8"))?;
                    let s = std::str::from_utf8(bytes).map_err(|_| self.err("invalid utf8"))?;
                    out.push_str(s);
                    self.pos = end;
                }
            }
        }
    }

    fn hex4(&mut self) -> Result<u16, JsonError> {
        let mut v: u16 = 0;
        for _ in 0..4 {
            let c = self.bump().ok_or_else(|| self.err("truncated \\u escape"))?;
            let d = (c as char).to_digit(16).ok_or_else(|| self.err("bad hex digit"))?;
            v = v * 16 + d as u16;
        }
        Ok(v)
    }

    fn parse_number(&mut self) -> Result<Json, JsonError> {
        let start = self.pos;
        if self.peek() == Some(b'-') {
            self.pos += 1;
        }
        while matches!(self.peek(), Some(c) if c.is_ascii_digit()) {
            self.pos += 1;
        }
        if self.peek() == Some(b'.') {
            self.pos += 1;
            while matches!(self.peek(), Some(c) if c.is_ascii_digit()) {
                self.pos += 1;
            }
        }
        if matches!(self.peek(), Some(b'e' | b'E')) {
            self.pos += 1;
            if matches!(self.peek(), Some(b'+' | b'-')) {
                self.pos += 1;
            }
            while matches!(self.peek(), Some(c) if c.is_ascii_digit()) {
                self.pos += 1;
            }
        }
        let text = std::str::from_utf8(&self.s[start..self.pos]).unwrap();
        text.parse::<f64>().map(Json::Num).map_err(|_| self.err("bad number"))
    }
}

fn utf8_width(first_byte: u8) -> usize {
    if first_byte & 0x80 == 0 {
        1
    } else if first_byte & 0xE0 == 0xC0 {
        2
    } else if first_byte & 0xF0 == 0xE0 {
        3
    } else {
        4
    }
}

/// Parse a standalone JSON value. `pub` (rather than the private `fn` this
/// started as) so `tests/board_yields.rs`, an integration test in its own
/// crate, can parse `tools/dump_board_yields.py`'s dump files with the same
/// reader -- `Result<_, FixtureError>` rather than the private `JsonError`
/// so that visibility change did not also need to make `JsonError` itself
/// `pub`.
pub fn parse_json(s: &str) -> Result<Json, FixtureError> {
    let mut p = JsonParser::new(s);
    let v = p.parse_value().map_err(FixtureError::from)?;
    p.skip_ws();
    if p.pos != p.s.len() {
        return Err(FixtureError::from(p.err("trailing data after JSON value")));
    }
    Ok(v)
}

// ======================================================== fixture types ==

/// The first line of a fixture file.
#[derive(Debug, Clone)]
pub struct Header {
    pub players: u8,
    pub seed: i64,
    pub bot: String,
    pub state_every: i64,
    pub max_plies: i64,
    pub engine_rev: Option<String>,
}

/// One decision: the legal-move list and the move chosen from it, plus the
/// digest (and, on some plies, the full state) of what applying it produced.
#[derive(Debug, Clone)]
pub struct Ply {
    pub ply: u32,
    pub decider: u8,
    pub phase: String,
    pub legal: Vec<Move>,
    pub chosen: Move,
    pub digest: String,
    /// `GameState.to_dict()` after `chosen` was applied, present only every
    /// `state_every` plies (always on the last ply of the file). Kept as raw
    /// `Json` rather than a typed `GameState` -- there is no `actions.rs` to
    /// replay into yet, and no `GameState::from_json` either; that conversion
    /// is exactly the "state-replay assertions" `differential.rs` marks
    /// `#[ignore]` until the module bodies land.
    pub state: Option<Json>,
}

/// The last line of a fixture file.
#[derive(Debug, Clone)]
pub struct Footer {
    pub plies: u32,
    pub game_over: bool,
    pub truncated: bool,
}

#[derive(Debug, Clone)]
pub enum Record {
    Header(Header),
    Ply(Ply),
    Footer(Footer),
}

#[derive(Debug)]
pub struct FixtureError {
    pub message: String,
    pub file: Option<PathBuf>,
    pub line: Option<usize>,
}

impl FixtureError {
    fn new(msg: impl Into<String>) -> Self {
        FixtureError { message: msg.into(), file: None, line: None }
    }

    fn with_context(mut self, path: &Path, line: usize) -> Self {
        self.file = Some(path.to_path_buf());
        self.line = Some(line);
        self
    }
}

impl fmt::Display for FixtureError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match (&self.file, self.line) {
            (Some(p), Some(l)) => write!(f, "{}:{l}: {}", p.display(), self.message),
            _ => write!(f, "{}", self.message),
        }
    }
}

impl std::error::Error for FixtureError {}

impl From<JsonError> for FixtureError {
    fn from(e: JsonError) -> Self {
        FixtureError::new(format!("json parse error at byte {}: {}", e.pos, e.msg))
    }
}

fn req<'a>(v: &'a Json, key: &str) -> Result<&'a Json, FixtureError> {
    v.get(key).ok_or_else(|| FixtureError::new(format!("missing field {key:?}")))
}

fn req_str(v: &Json, key: &str) -> Result<String, FixtureError> {
    req(v, key)?
        .as_str()
        .map(str::to_owned)
        .ok_or_else(|| FixtureError::new(format!("field {key:?} is not a string")))
}

fn req_num(v: &Json, key: &str) -> Result<f64, FixtureError> {
    req(v, key)?
        .as_f64()
        .ok_or_else(|| FixtureError::new(format!("field {key:?} is not a number")))
}

fn req_bool(v: &Json, key: &str) -> Result<bool, FixtureError> {
    req(v, key)?
        .as_bool()
        .ok_or_else(|| FixtureError::new(format!("field {key:?} is not a bool")))
}

fn opt_str(v: &Json, key: &str) -> Option<String> {
    match v.get(key) {
        Some(Json::Str(s)) => Some(s.clone()),
        _ => None,
    }
}

// ------------------------------------------------------- move mapping ----

fn move_card(arr: &[Json], tag: &str, idx: usize) -> Result<CardId, FixtureError> {
    let name = arr
        .get(idx)
        .and_then(Json::as_str)
        .ok_or_else(|| FixtureError::new(format!("{tag}: missing card name at index {idx}")))?;
    CardId::by_name(name).ok_or_else(|| {
        FixtureError::new(format!("{tag}: card {name:?} has no CardId -- type layer is incomplete"))
    })
}

fn move_u8(arr: &[Json], tag: &str, idx: usize) -> Result<u8, FixtureError> {
    let n = arr
        .get(idx)
        .and_then(Json::as_f64)
        .ok_or_else(|| FixtureError::new(format!("{tag}: missing number at index {idx}")))?;
    Ok(n as u8)
}

fn pact_side(arr: &[Json], tag: &str) -> Result<PactSide, FixtureError> {
    match arr.get(3).and_then(Json::as_str) {
        Some("A") => Ok(PactSide::A),
        Some("B") => Ok(PactSide::B),
        Some("") => Ok(PactSide::Unspecified),
        other => Err(FixtureError::new(format!("{tag}: bad pact side {other:?}"))),
    }
}

fn churchill_choice(arr: &[Json], tag: &str) -> Result<ChurchillChoice, FixtureError> {
    match arr.get(1).and_then(Json::as_str) {
        Some("culture") => Ok(ChurchillChoice::Culture),
        Some("military") => Ok(ChurchillChoice::Military),
        other => Err(FixtureError::new(format!("{tag}: bad churchill choice {other:?}"))),
    }
}

/// Parse one `["tag", ...]` JSON array into a [`Move`].
///
/// This is the ONE place in the crate that maps a Python move tag string to
/// a `Move` variant -- see `moves.rs`'s own docstring, which promises the
/// variant list is derived from every move tuple the Python engine
/// constructs. This function is the inverse of that promise, checked here
/// against real games rather than against a manual reading of
/// `engine/actions.py` and `engine/interact.py`. An unmapped tag or a card
/// name with no `CardId` is exactly the finding this whole harness exists to
/// surface, so both fail loudly here rather than silently coercing to
/// something plausible.
pub fn parse_move(v: &Json) -> Result<Move, FixtureError> {
    let arr = v
        .as_arr()
        .ok_or_else(|| FixtureError::new("move is not a JSON array"))?;
    let tag = arr
        .first()
        .and_then(Json::as_str)
        .ok_or_else(|| FixtureError::new("move array has no tag string at index 0"))?;
    Ok(match tag {
        "take" => Move::Take { slot: move_u8(arr, tag, 1)? },
        "build" => Move::Build { card: move_card(arr, tag, 1)? },
        "develop" => Move::Develop { card: move_card(arr, tag, 1)? },
        "upgrade" => Move::Upgrade { from: move_card(arr, tag, 1)?, to: move_card(arr, tag, 2)? },
        "wonder_step" => Move::WonderStep { steps: move_u8(arr, tag, 1)? },
        "pop" => Move::Pop,
        "pop_free" => Move::PopFree,
        "revolution" => Move::Revolution { card: move_card(arr, tag, 1)? },
        "play_leader" => Move::PlayLeader { card: move_card(arr, tag, 1)? },
        "play_action" => Move::PlayAction { card: move_card(arr, tag, 1)? },
        "destroy" => Move::Destroy { card: move_card(arr, tag, 1)? },
        "play_tactic" => Move::PlayTactic { card: move_card(arr, tag, 1)? },
        "copy_tactic" => Move::CopyTactic { card: move_card(arr, tag, 1)? },
        "aggression" => Move::Aggression { card: move_card(arr, tag, 1)?, target: move_u8(arr, tag, 2)? },
        "war" => Move::War { card: move_card(arr, tag, 1)?, target: move_u8(arr, tag, 2)? },
        "offer_pact" => Move::OfferPact {
            card: move_card(arr, tag, 1)?,
            target: move_u8(arr, tag, 2)?,
            side: pact_side(arr, tag)?,
        },
        "cancel_pact" => Move::CancelPact { owner: move_u8(arr, tag, 1)? },
        "prepare_event" => Move::PrepareEvent { card: move_card(arr, tag, 1)? },
        "bid" => Move::Bid { n: move_u8(arr, tag, 1)? },
        "bid_pass" => Move::BidPass,
        "defend" => Move::Defend { card: move_card(arr, tag, 1)? },
        "defend_done" => Move::DefendDone,
        "send_unit" => Move::SendUnit { card: move_card(arr, tag, 1)? },
        "send_bonus" => Move::SendBonus { card: move_card(arr, tag, 1)? },
        "send_discard" => Move::SendDiscard { card: move_card(arr, tag, 1)? },
        "send_done" => Move::SendDone,
        "choose" => Move::Choose { n: move_u8(arr, tag, 1)? },
        "churchill" => Move::Churchill { choice: churchill_choice(arr, tag)? },
        "end_turn" => Move::EndTurn,
        "pol_pass" => Move::PolPass,
        "resign" => Move::Resign,
        "remove_leader_yellow" => Move::RemoveLeaderYellow,
        "columbus_colonize" => Move::ColumbusColonize { card: move_card(arr, tag, 1)? },
        "barbarossa" => Move::Barbarossa { card: move_card(arr, tag, 1)? },
        "bach_theater" => Move::BachTheater { from: move_card(arr, tag, 1)?, to: move_card(arr, tag, 2)? },
        other => {
            return Err(FixtureError::new(format!(
                "unknown move tag {other:?} -- Move enum in moves.rs has no matching variant"
            )))
        }
    })
}

// -------------------------------------------------------- record parsing -

fn parse_header(v: &Json) -> Result<Header, FixtureError> {
    Ok(Header {
        players: req_num(v, "players")? as u8,
        seed: req_num(v, "seed")? as i64,
        bot: req_str(v, "bot")?,
        state_every: req_num(v, "state_every")? as i64,
        max_plies: req_num(v, "max_plies")? as i64,
        engine_rev: opt_str(v, "engine_rev"),
    })
}

fn parse_ply(v: &Json) -> Result<Ply, FixtureError> {
    let legal_arr = req(v, "legal")?
        .as_arr()
        .ok_or_else(|| FixtureError::new("\"legal\" is not an array"))?;
    let mut legal = Vec::with_capacity(legal_arr.len());
    for (i, mv) in legal_arr.iter().enumerate() {
        legal.push(parse_move(mv).map_err(|e| {
            FixtureError::new(format!("legal[{i}]: {}", e.message))
        })?);
    }
    let chosen = parse_move(req(v, "chosen")?)
        .map_err(|e| FixtureError::new(format!("chosen: {}", e.message)))?;
    Ok(Ply {
        ply: req_num(v, "ply")? as u32,
        decider: req_num(v, "decider")? as u8,
        phase: req_str(v, "phase")?,
        legal,
        chosen,
        digest: req_str(v, "digest")?,
        state: v.get("state").cloned(),
    })
}

fn parse_footer(v: &Json) -> Result<Footer, FixtureError> {
    Ok(Footer {
        plies: req_num(v, "plies")? as u32,
        game_over: req_bool(v, "game_over")?,
        truncated: req_bool(v, "truncated")?,
    })
}

/// Parse one JSON-Lines record (one line of a fixture file).
pub fn parse_record(line: &str) -> Result<Record, FixtureError> {
    let v = parse_json(line)?;
    let kind = req_str(&v, "kind")?;
    match kind.as_str() {
        "header" => Ok(Record::Header(parse_header(&v)?)),
        "ply" => Ok(Record::Ply(parse_ply(&v)?)),
        "footer" => Ok(Record::Footer(parse_footer(&v)?)),
        other => Err(FixtureError::new(format!("unknown record kind {other:?}"))),
    }
}

/// Read and parse a whole fixture file, in line order.
pub fn read_fixture_file(path: &Path) -> Result<Vec<Record>, FixtureError> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| FixtureError::new(format!("{}: {e}", path.display())))?;
    let mut out = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let rec = parse_record(line).map_err(|e| e.with_context(path, i + 1))?;
        out.push(rec);
    }
    Ok(out)
}

/// Every `*.jsonl` fixture file directly inside `dir`, sorted by filename so
/// a test run is deterministic regardless of directory-listing order.
pub fn fixture_files(dir: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|e| e == "jsonl").unwrap_or(false))
        .collect();
    files.sort();
    Ok(files)
}

// ================================================== GameState::from_json ==
//
// Loads a `GameState.to_dict()` dump (`tools/dump_fixtures.py`'s "state"
// field) into a Rust `GameState`, so `tests/differential.rs` can replay a
// fixture from a known-good point rather than needing `game::new_game`
// (`game.rs` is not ported -- see `apply.rs`'s top doc comment).
//
// Three Python `GameState` fields have NO home in `state.rs` and are
// rejected rather than silently dropped if the dumped state actually needs
// them:
//
//   * `pending` / `queue` -- `interact.rs`'s decision queue. Not ported;
//     `state.rs` has no field for it (apply.rs's top doc comment). Checked
//     by `must_be_empty` below -- erroring loudly the one time it would
//     matter (silently dropping a non-empty decision queue would make a
//     loaded state look further along than it is: whose move is next, and
//     what is legal, both depend on it) rather than every time.
//
// A second and third field are silently dropped even when non-empty,
// deliberately NOT gated by `must_be_empty`:
//
//   * `seeded_by` (event name -> which player prepared it) is read ONLY by
//     the bots' own evaluation heuristics (`bots/weighted.py`,
//     `bots/counting.py`, `bots/neural_encode.py` -- grepped 2026-08-05,
//     nothing in `engine/actions.py`, `costs.py`, `economy.py` or
//     `effects.py` touches it) -- never by `legal_moves`/`apply` or anything
//     `costs.rs`/`economy.rs`/`effects.rs` port. This replay never calls a
//     bot (it replays the fixture's already-`chosen` move), so it never
//     needs this field. It is also the ONE dict that becomes permanently
//     non-empty almost immediately (any `PrepareEvent` adds an entry that is
//     never removed) -- gating on it the way `pending`/`queue` are gated
//     would reject nearly every snapshot in the game after its opening
//     plies, which was tried and measured: 327 of 327 later anchors failed
//     to load. `must_be_empty` would be technically defensible but
//     practically self-defeating here.
// `one_time_discount` used to be listed here as a third silently-dropped
// field ("has no home on `PlayerState` at all"). It is LOADED now, by
// `one_time_discount_field` below, into `state::OneTimeDiscount` -- and it
// had to be: it is non-empty on most plies of 7 of the 9 fixtures, and
// `costs.rs`/`economy.rs` read it, so dropping it made Rust overcharge for
// every build, develop and population increase in those replays.
//
// `has_military` (always `true` for the complete base-game card table --
// see `legal.rs`'s `politics_moves` comment) and `final_scores` (only
// meaningful once `game_over`, and nothing here scores a finished game) are
// likewise not loaded; both are read-only derived/terminal facts, never
// inputs to `legal_moves`/`apply`. `log` is dropped same as
// `tools/dump_fixtures.py::state_digest` drops it.

// ------------------------------------------- the decision queue (pending) -
//
// `pending` and `queue` used to be rejected outright by `must_be_empty`
// (deleted with this change): `state.rs` had no field for either, and
// silently dropping a non-empty decision queue would make a loaded state look
// further along than it is -- whose move is next, and what is legal, both
// depend on it. 247 of the fixtures' anchor states were unloadable for that
// reason alone. `state::PendingStack` / `state::Queue` exist now, so this
// section loads them.
//
// Every option list, every context key and every queue payload is mapped
// EXPLICITLY, per tag, and an unrecognised tag / option shape / context key
// is an error. That is the point: Python's option lists are untyped JSON, so
// the only way to know a `("choose", 3)` means the same thing on both sides
// is to name what each option IS. A silent fallback here would produce a
// state that loads and then diverges at the next ply for no visible reason.

/// A card name from a JSON string, in a decision payload.
fn pend_card(v: &Json, tag: &str) -> Result<CardId, FixtureError> {
    let name = v
        .as_str()
        .ok_or_else(|| FixtureError::new(format!("{tag}: expected a card name string")))?;
    CardId::by_name(name)
        .ok_or_else(|| FixtureError::new(format!("{tag}: unknown card {name:?}")))
}

fn pend_u8(v: &Json, key: &str, tag: &str) -> Result<u8, FixtureError> {
    Ok(req_num(v, key).map_err(|e| FixtureError::new(format!("{tag}: {e}")))? as u8)
}

fn pend_i16(v: &Json, key: &str, tag: &str) -> Result<i16, FixtureError> {
    Ok(req_num(v, key).map_err(|e| FixtureError::new(format!("{tag}: {e}")))? as i16)
}

/// The `ctx` sub-object of a `choice`, or an empty object when absent.
fn ctx_of(v: &Json) -> Json {
    match v.get("ctx") {
        Some(o @ Json::Obj(_)) => o.clone(),
        _ => Json::Obj(Vec::new()),
    }
}

/// Card names (+ an optional trailing keyword) into a [`ChoiceOption`] list.
fn card_options_json(arr: &[Json], tag: &str, trailing: Option<Keyword>) -> Result<OptionList, FixtureError> {
    let mut out = OptionList::new();
    for (i, item) in arr.iter().enumerate() {
        let last = i + 1 == arr.len();
        if let (Some(word), Some(s)) = (trailing, item.as_str()) {
            if last && s == keyword_text(word) {
                out.push(ChoiceOption::Word(word));
                continue;
            }
        }
        out.push(ChoiceOption::Card(pend_card(item, tag)?));
    }
    Ok(out)
}

/// The exact JSON spelling of each keyword option, so the loader and the
/// engine cannot drift on what `"stop"` means.
fn keyword_text(w: Keyword) -> &'static str {
    match w {
        Keyword::Stop => "stop",
        Keyword::Skip => "skip",
        Keyword::Science => "science",
        Keyword::Food => "food",
        Keyword::Resources => "resources",
        Keyword::Accept => "accept",
        Keyword::Refuse => "refuse",
        Keyword::Leader => "leader",
        Keyword::Wonder => "wonder",
    }
}

fn word_options(arr: &[Json], tag: &str, allowed: &[Keyword]) -> Result<OptionList, FixtureError> {
    let mut out = OptionList::new();
    for item in arr {
        let s = item
            .as_str()
            .ok_or_else(|| FixtureError::new(format!("{tag}: expected a keyword string")))?;
        let w = allowed
            .iter()
            .copied()
            .find(|w| keyword_text(*w) == s)
            .ok_or_else(|| FixtureError::new(format!("{tag}: unexpected option {s:?}")))?;
        out.push(ChoiceOption::Word(w));
    }
    Ok(out)
}

/// One `{"food": n}` / `{"resources": n}` branch of an event's `choose`
/// block. Any OTHER key is an error, not a zero -- `state::GainOption`'s doc
/// comment records that the base game prints exactly these two, so a third
/// means the data grew and this must grow with it.
fn gain_option(v: &Json, tag: &str) -> Result<GainOption, FixtureError> {
    let Json::Obj(fields) = v else {
        return Err(FixtureError::new(format!("{tag}: gain option is not an object")));
    };
    let mut out = GainOption::default();
    for (k, val) in fields {
        let n = val
            .as_f64()
            .ok_or_else(|| FixtureError::new(format!("{tag}: {k:?} is not a number")))?
            as i16;
        match k.as_str() {
            "food" => out.food = n,
            "resources" => out.resources = n,
            other => {
                return Err(FixtureError::new(format!(
                    "{tag}: gain option key {other:?} is not one of food/resources -- \
                     see state::GainOption"
                )))
            }
        }
    }
    Ok(out)
}

fn parse_card_type(s: &str, tag: &str) -> Result<CardType, FixtureError> {
    Ok(match s {
        "farm" => CardType::Farm,
        "mine" => CardType::Mine,
        "lab" => CardType::Lab,
        "temple" => CardType::Temple,
        "library" => CardType::Library,
        "arena" => CardType::Arena,
        "theater" => CardType::Theater,
        "infantry" => CardType::Infantry,
        "cavalry" => CardType::Cavalry,
        "artillery" => CardType::Artillery,
        "air" => CardType::Air,
        other => {
            return Err(FixtureError::new(format!(
                "{tag}: card type {other:?} is not a worker-holding type"
            )))
        }
    })
}

/// One `pending` entry.
fn parse_pending(v: &Json) -> Result<Pending, FixtureError> {
    let kind = req_str(v, "kind")?;
    Ok(match kind.as_str() {
        "choice" => Pending::Choice(parse_choice(v)?),
        "auction" => {
            let tag = "pending.auction";
            let active_json = req_arr(v, "active", tag)?;
            let mut active = [0u8; MAX_PLAYERS];
            if active_json.len() > MAX_PLAYERS {
                return Err(FixtureError::new(format!("{tag}: {} bidders", active_json.len())));
            }
            for (i, a) in active_json.iter().enumerate() {
                active[i] = a
                    .as_f64()
                    .ok_or_else(|| FixtureError::new(format!("{tag}.active[{i}]: not a number")))?
                    as u8;
            }
            Pending::Auction(Auction::restore(
                pend_card(req(v, "card")?, tag)?,
                &active[..active_json.len()],
                pend_u8(v, "pos", tag)?,
                pend_u8(v, "bid", tag)?,
                opt_u8(v, "high")?,
                pend_u8(v, "player", tag)?,
            ))
        }
        "defense" => {
            let tag = "pending.defense";
            Pending::Defense(Defense {
                player: pend_u8(v, "player", tag)?,
                attacker: pend_u8(v, "attacker", tag)?,
                card: pend_card(req(v, "card")?, tag)?,
                atk: req_num(v, "atk")? as i32,
                dfn: req_num(v, "dfn")? as i32,
                spent: pend_u8(v, "spent", tag)?,
                budget: pend_u8(v, "budget", tag)?,
            })
        }
        "colonize" => {
            let tag = "pending.colonize";
            Pending::Colonize(Colonize {
                player: pend_u8(v, "player", tag)?,
                card: pend_card(req(v, "card")?, tag)?,
                bid: pend_u8(v, "bid", tag)?,
                units: card_list(v, "units", tag)?,
                bonuses: card_list(v, "bonuses", tag)?,
                discards: card_list(v, "discards", tag)?,
                pool: card_list(v, "pool", tag)?,
                bpool: card_list(v, "bpool", tag)?,
                dpool: card_list(v, "dpool", tag)?,
            })
        }
        other => {
            return Err(FixtureError::new(format!(
                "pending: unknown decision kind {other:?} -- state::Pending has no variant"
            )))
        }
    })
}

/// A `choice` entry: its `tag`+`ctx` become a [`ChoiceKind`] and its
/// `options` become an [`OptionList`], both keyed off the same tag so the
/// two can never be parsed against different rules.
fn parse_choice(v: &Json) -> Result<Choice, FixtureError> {
    let tag = req_str(v, "tag")?;
    let player = pend_u8(v, "player", &tag)?;
    let opts = req_arr(v, "options", "pending.choice")?;
    let ctx = ctx_of(v);
    let t = tag.as_str();
    let (kind, options) = match t {
        "gain_block" => {
            let mut out = OptionList::new();
            for o in opts {
                out.push(ChoiceOption::Gain(gain_option(o, t)?));
            }
            (ChoiceKind::GainBlock, out)
        }
        "free_civil" => {
            let mut out = OptionList::new();
            for o in opts {
                out.push(ChoiceOption::Move(parse_move(o)?));
            }
            (ChoiceKind::FreeCivil { discount: pend_i16(&ctx, "discount", t)? }, out)
        }
        "food_or_res" => (
            ChoiceKind::FoodOrRes { n: pend_i16(&ctx, "n", t)? },
            word_options(opts, t, &[Keyword::Food, Keyword::Resources])?,
        ),
        "free_build" => (ChoiceKind::FreeBuild, card_options_json(opts, t, Some(Keyword::Skip))?),
        "destroy_own" => (ChoiceKind::DestroyOwn, card_options_json(opts, t, None)?),
        "lose_pop" => (ChoiceKind::LosePop, card_options_json(opts, t, None)?),
        "lose_colony" => (ChoiceKind::LoseColony, card_options_json(opts, t, None)?),
        "flip_wonder" => (ChoiceKind::FlipWonder, card_options_json(opts, t, None)?),
        "discard_military" => {
            (ChoiceKind::DiscardMilitary, card_options_json(opts, t, None)?)
        }
        "raid" => (
            ChoiceKind::Raid {
                victim: pend_u8(&ctx, "victim", t)?,
                // Python's `ctx.get("loot", True)`.
                loot: ctx.get("loot").and_then(Json::as_bool).unwrap_or(true),
            },
            card_options_json(opts, t, None)?,
        ),
        "annex" => (
            ChoiceKind::Annex { victim: pend_u8(&ctx, "victim", t)? },
            card_options_json(opts, t, None)?,
        ),
        "infiltrate" => (
            ChoiceKind::Infiltrate {
                victim: pend_u8(&ctx, "victim", t)?,
                per: ctx.get("per").and_then(Json::as_f64).unwrap_or(3.0) as u8,
            },
            word_options(opts, t, &[Keyword::Leader, Keyword::Wonder])?,
        ),
        "pact_offer" => (
            ChoiceKind::PactOffer {
                owner: pend_u8(&ctx, "owner", t)?,
                card: pend_card(req(&ctx, "name")?, t)?,
                a: pend_u8(&ctx, "a", t)?,
                b: pend_u8(&ctx, "b", t)?,
            },
            word_options(opts, t, &[Keyword::Accept, Keyword::Refuse])?,
        ),
        "take_row" => {
            // Row slot indices, then a trailing "stop".
            let mut out = OptionList::new();
            for o in opts {
                match o {
                    Json::Num(n) => out.push(ChoiceOption::Slot(*n as u8)),
                    Json::Str(s) if s == "stop" => out.push(ChoiceOption::Word(Keyword::Stop)),
                    other => {
                        return Err(FixtureError::new(format!(
                            "take_row: unexpected option {other:?}"
                        )))
                    }
                }
            }
            (ChoiceKind::TakeRow { budget: pend_i16(&ctx, "budget", t)? }, out)
        }
        "war_tech" => {
            // A leading "science", then card names -- and the position of
            // "science" is load-bearing (`interact::WAR_TECH_SCIENCE_IDX`).
            let mut out = OptionList::new();
            for (i, o) in opts.iter().enumerate() {
                match o.as_str() {
                    Some("science") if i == 0 => out.push(ChoiceOption::Word(Keyword::Science)),
                    _ => out.push(ChoiceOption::Card(pend_card(o, t)?)),
                }
            }
            (
                ChoiceKind::WarTech {
                    victim: pend_u8(&ctx, "victim", t)?,
                    budget: pend_i16(&ctx, "budget", t)?,
                },
                out,
            )
        }
        other => {
            return Err(FixtureError::new(format!(
                "pending.choice: unknown tag {other:?} -- state::ChoiceKind has no variant \
                 (interact._CHOICE has {other:?}, so one of the two registries is stale)"
            )))
        }
    };
    Ok(Choice { player, kind, options })
}

/// One `queue` entry.
fn parse_queue_item(v: &Json) -> Result<QueueItem, FixtureError> {
    let tag = req_str(v, "tag")?;
    let t = tag.as_str();
    let player = pend_u8(v, "player", t)?;
    // Python's `int(item.get("n", 1))` / `item.get("per", 3)` defaults.
    let n = || v.get("n").and_then(Json::as_f64).unwrap_or(1.0) as u8;
    Ok(match t {
        "choose" => {
            let mut options = GainOptions::new();
            for o in req_arr(v, "options", "queue.choose")? {
                options.push(gain_option(o, t)?);
            }
            QueueItem::Choose { player, options }
        }
        "free_civil" => QueueItem::FreeCivil {
            player,
            kind: parse_free_civil_kind(&req_str(v, "kind")?)?,
            discount: v.get("discount").and_then(Json::as_f64).unwrap_or(0.0) as i16,
            revolt_ok: v.get("revolt_ok").and_then(Json::as_bool).unwrap_or(false),
        },
        "card_gains" => QueueItem::CardGains { player, gains: parse_card_gains(v)? },
        "free_build" => QueueItem::FreeBuild { player, spec: parse_free_build_spec(v)? },
        "destroy_own" => QueueItem::DestroyOwn { player },
        "lose_pop" => QueueItem::LosePop { player, n: n() },
        "lose_colony" => QueueItem::LoseColony { player },
        "flip_wonder" => {
            // Python passes a list of age strings, defaulting to ["A", "I"].
            let mut ages = 0u8;
            match v.get("ages") {
                Some(Json::Arr(a)) => {
                    for item in a {
                        let s = item.as_str().ok_or_else(|| {
                            FixtureError::new("queue.flip_wonder: age is not a string")
                        })?;
                        ages |= 1 << (parse_age(s, "queue.flip_wonder")? as u8);
                    }
                }
                _ => ages = (1 << (Age::A as u8)) | (1 << (Age::I as u8)),
            }
            QueueItem::FlipWonder { player, ages }
        }
        "discard_military" => QueueItem::DiscardMilitary { player, n: n() },
        "end_of_turn" => QueueItem::EndOfTurn { player },
        "auto_skip_politics" => QueueItem::AutoSkipPolitics { player },
        "raid" => QueueItem::Raid {
            player,
            victim: pend_u8(v, "victim", t)?,
            // Python's `C.level(item.get("max_age", "A"))`.
            max_age: match v.get("max_age").and_then(Json::as_str) {
                Some(s) => parse_age(s, "queue.raid.max_age")?,
                None => Age::A,
            },
            no_loot: v.get("no_loot").and_then(Json::as_bool).unwrap_or(false),
        },
        "annex" => QueueItem::Annex { player, victim: pend_u8(v, "victim", t)? },
        "infiltrate" => QueueItem::Infiltrate {
            player,
            victim: pend_u8(v, "victim", t)?,
            per: v.get("per").and_then(Json::as_f64).unwrap_or(3.0) as u8,
        },
        "take_row" => QueueItem::TakeRow {
            player,
            budget: v.get("budget").and_then(Json::as_f64).unwrap_or(0.0) as i16,
        },
        // `"gains"` is registered in `interact._QUEUE_ITEMS` and enqueued by
        // nothing (see `interact.rs`'s top doc comment). Reaching it here
        // would mean a producer appeared, which is worth failing on rather
        // than absorbing.
        other => {
            return Err(FixtureError::new(format!(
                "queue: unknown tag {other:?} -- state::QueueItem has no variant"
            )))
        }
    })
}

fn parse_free_civil_kind(
    s: &str,
) -> Result<crate::card_table::FreeCivilActionValue, FixtureError> {
    use crate::card_table::FreeCivilActionValue as V;
    Ok(match s {
        "buildOrUpgradeFarmOrMine" => V::BuildOrUpgradeFarmOrMine,
        "buildOrUpgradeUrbanBuilding" => V::BuildOrUpgradeUrbanBuilding,
        "increasePopulation" => V::IncreasePopulation,
        "buildOneWonderStage" => V::BuildOneWonderStage,
        "developTechnology" => V::DevelopTechnology,
        "upgradeFarmMineOrUrbanBuilding" => V::UpgradeFarmMineOrUrbanBuilding,
        other => {
            return Err(FixtureError::new(format!(
                "queue.free_civil: unknown ordered action {other:?}"
            )))
        }
    })
}

/// A `card_gains` payload -- Python's `_GAIN_KEYS`, and nothing else.
fn parse_card_gains(v: &Json) -> Result<CardGains, FixtureError> {
    let mut out = CardGains::default();
    let Some(Json::Obj(fields)) = v.get("gains") else { return Ok(out) };
    for (k, val) in fields {
        let n = val
            .as_f64()
            .ok_or_else(|| FixtureError::new(format!("queue.card_gains: {k:?} is not a number")))?
            as i16;
        match k.as_str() {
            "gainScience" => out.science = n,
            "gainCulture" => out.culture = n,
            "gainFood" => out.food = n,
            "gainResources" => out.resources = n,
            "gainPopulation" => out.population = n,
            "gainFoodOrResources" => out.food_or_resources = n,
            other => {
                return Err(FixtureError::new(format!(
                    "queue.card_gains: key {other:?} is not one of actions.py's _GAIN_KEYS"
                )))
            }
        }
    }
    Ok(out)
}

fn parse_free_build_spec(v: &Json) -> Result<FreeBuildSpec, FixtureError> {
    let Some(spec) = v.get("spec") else {
        return Err(FixtureError::new("queue.free_build: missing spec"));
    };
    let mut out = FreeBuildSpec::default();
    let Json::Obj(fields) = spec else {
        return Err(FixtureError::new("queue.free_build: spec is not an object"));
    };
    for (k, val) in fields {
        match k.as_str() {
            "card" => out.card = pend_card(val, "queue.free_build.spec.card")?,
            "age" => {
                let s = val.as_str().ok_or_else(|| {
                    FixtureError::new("queue.free_build.spec.age: not a string")
                })?;
                out.age = Some(parse_age(s, "queue.free_build.spec.age")?);
            }
            "type" => {
                let s = val.as_str().ok_or_else(|| {
                    FixtureError::new("queue.free_build.spec.type: not a string")
                })?;
                out.kind = Some(parse_card_type(s, "queue.free_build.spec")?);
            }
            "cost" => {
                out.cost = val.as_f64().ok_or_else(|| {
                    FixtureError::new("queue.free_build.spec.cost: not a number")
                })? as u16
            }
            // `requiresAvailableWorker` is not a filter on the option list:
            // `_q_free_build` already returns early when `workers_free == 0`,
            // which is the same test for every base-game printing of the key
            // (both print it `true`). Nothing to store.
            "requiresAvailableWorker" => {}
            other => {
                return Err(FixtureError::new(format!(
                    "queue.free_build.spec: unknown key {other:?}"
                )))
            }
        }
    }
    Ok(out)
}

fn pending_field(v: &Json) -> Result<PendingStack, FixtureError> {
    let mut out = PendingStack::new();
    let Some(arr) = v.get("pending").and_then(Json::as_arr) else { return Ok(out) };
    if arr.len() > crate::state::MAX_PENDING {
        return Err(FixtureError::new(format!(
            "state.pending is {} deep, MAX_PENDING is {}",
            arr.len(),
            crate::state::MAX_PENDING
        )));
    }
    for item in arr {
        out.push(parse_pending(item)?);
    }
    Ok(out)
}

fn queue_field(v: &Json) -> Result<Queue, FixtureError> {
    let mut out = Queue::new();
    let Some(arr) = v.get("queue").and_then(Json::as_arr) else { return Ok(out) };
    if arr.len() > crate::state::MAX_QUEUE {
        return Err(FixtureError::new(format!(
            "state.queue holds {} items, MAX_QUEUE is {}",
            arr.len(),
            crate::state::MAX_QUEUE
        )));
    }
    for item in arr {
        out.push_back(parse_queue_item(item)?);
    }
    Ok(out)
}

// `player_has_one_time_discount(v, player_idx) -> bool` lived here until
// 2026-08-05: a peek at the RAW dump, used by `tests/differential.rs` to
// EXCUSE a divergence ("Rust priced this move without the discount Python
// applied"). `one_time_discount_field` below loads the discount for real
// now, so nothing needs excusing and nothing called it. Deleted rather than
// left `pub`: its only purpose was to describe a gap that no longer exists.

/// `players[i].one_time_discount` -> [`OneTimeDiscount`].
///
/// The dump's shape is a dict of dicts -- `{"build": {"resources": 1},
/// "developTechnology": {"science": 1}, "increasePopulation": {"food": 1}}`
/// -- and it is CLOSED: exactly one card in `data/*.json` ("Development of
/// Civil Life", the Age A event) writes it, `engine/events.py:360` copies it
/// through verbatim, and `engine/effects.py`/`engine/economy.py` read
/// exactly these three paths. So an unrecognised outer key, an unrecognised
/// inner key, or a non-object value is an ERROR here rather than a silent
/// zero: a discount this loader dropped would make Rust overcharge for the
/// rest of the replay, which is precisely the divergence
/// `tests/differential.rs` exists to catch, and it must not be caused by the
/// loader itself.
///
/// Absent or `{}` (the field only appears once an event has granted it) is
/// the zero discount, not an error.
fn one_time_discount_field(v: &Json, tag: &str) -> Result<OneTimeDiscount, FixtureError> {
    let mut out = OneTimeDiscount::default();
    let Some(raw) = v.get("one_time_discount") else { return Ok(out) };
    let Json::Obj(entries) = raw else {
        return Err(FixtureError::new(format!("{tag}.one_time_discount: not an object")));
    };
    for (key, block) in entries {
        let path = format!("{tag}.one_time_discount.{key}");
        let (inner_key, slot): (&str, &mut i16) = match key.as_str() {
            "build" => ("resources", &mut out.build_resources),
            "developTechnology" => ("science", &mut out.develop_science),
            "increasePopulation" => ("food", &mut out.pop_food),
            other => {
                return Err(FixtureError::new(format!(
                    "{tag}.one_time_discount: unknown key {other:?} -- the only card that \
                     grants a one-time discount prints build/developTechnology/\
                     increasePopulation; a fourth would need a field on \
                     state::OneTimeDiscount and a reader, not a silent drop"
                )))
            }
        };
        let Json::Obj(fields) = block else {
            return Err(FixtureError::new(format!("{path}: not an object")));
        };
        for (k, v) in fields {
            if k != inner_key {
                return Err(FixtureError::new(format!(
                    "{path}: unknown key {k:?}, expected {inner_key:?}"
                )));
            }
            *slot = v
                .as_f64()
                .ok_or_else(|| FixtureError::new(format!("{path}.{k}: not a number")))?
                as i16;
        }
    }
    Ok(out)
}

fn parse_age(s: &str, tag: &str) -> Result<Age, FixtureError> {
    Ok(match s {
        "A" => Age::A,
        "I" => Age::I,
        "II" => Age::II,
        "III" => Age::III,
        "IV" => Age::IV,
        other => return Err(FixtureError::new(format!("{tag}: unknown age {other:?}"))),
    })
}

/// `null` -> `CardId::NONE`, a string -> `CardId::by_name`. The one place a
/// dumped card-or-nothing field becomes a `CardId`.
fn card_id_opt(v: &Json, tag: &str) -> Result<CardId, FixtureError> {
    match v {
        Json::Null => Ok(CardId::NONE),
        Json::Str(s) => CardId::by_name(s)
            .ok_or_else(|| FixtureError::new(format!("{tag}: unknown card {s:?}"))),
        other => Err(FixtureError::new(format!("{tag}: expected string or null, got {other:?}"))),
    }
}

fn req_arr<'a>(v: &'a Json, key: &str, tag: &str) -> Result<&'a [Json], FixtureError> {
    req(v, key)?
        .as_arr()
        .ok_or_else(|| FixtureError::new(format!("{tag}.{key}: not an array")))
}

/// A JSON array of card names into a fixed-capacity [`CardList`]. List order
/// is preserved -- draw order / hand order is real state (DESIGN.md).
fn card_list<const N: usize>(v: &Json, key: &str, tag: &str) -> Result<CardList<N>, FixtureError> {
    let arr = req_arr(v, key, tag)?;
    let mut out = CardList::<N>::new();
    for (i, item) in arr.iter().enumerate() {
        let name = item
            .as_str()
            .ok_or_else(|| FixtureError::new(format!("{tag}.{key}[{i}]: not a string")))?;
        let id = CardId::by_name(name).ok_or_else(|| {
            FixtureError::new(format!("{tag}.{key}[{i}]: unknown card {name:?}"))
        })?;
        out.push(id);
    }
    Ok(out)
}

/// `p.techs`: `{name: {name, workers, stored}}`. Inserted in the JSON
/// object's own key order, which -- now that `tools/dump_fixtures.py` writes
/// the "state" snapshot with `sort_keys=False` (`_FILE_JSON_KW`; see that
/// module's comment on why the old `sort_keys=True` dump silently discarded
/// this) -- IS Python's dict insertion order, i.e. tableau BUILD order.
/// `Tableau::insert` preserves exactly that order, matching `state.rs`'s
/// documented contract (`economy.lose_population` walks the first
/// worker-holding card in build order).
fn techs_tableau(v: &Json, tag: &str) -> Result<Tableau, FixtureError> {
    let obj = match req(v, "techs")? {
        Json::Obj(fields) => fields,
        other => return Err(FixtureError::new(format!("{tag}.techs: not an object, got {other:?}"))),
    };
    let mut t = Tableau::new();
    for (name, val) in obj {
        let id = CardId::by_name(name).ok_or_else(|| {
            FixtureError::new(format!("{tag}.techs[{name:?}]: unknown card"))
        })?;
        let workers = req_num(val, "workers")? as u8;
        let stored = req_num(val, "stored")? as u8;
        t.insert(id, TechSlot { workers, stored });
    }
    Ok(t)
}

/// `p.wonder`: `null` or `{name, steps_built}` -> `(CardId, wonder_steps)`.
fn wonder_field(v: &Json, tag: &str) -> Result<(CardId, u8), FixtureError> {
    match req(v, "wonder")? {
        Json::Null => Ok((CardId::NONE, 0)),
        obj @ Json::Obj(_) => {
            let name = req_str(obj, "name")?;
            let steps = req_num(obj, "steps_built")? as u8;
            let id = CardId::by_name(&name)
                .ok_or_else(|| FixtureError::new(format!("{tag}.wonder: unknown card {name:?}")))?;
            Ok((id, steps))
        }
        other => Err(FixtureError::new(format!("{tag}.wonder: expected object or null, got {other:?}"))),
    }
}

/// `p.taken_leader_ages`: a list of age strings -> the bitmask `state.rs`
/// stores instead (see `PlayerState::taken_leader_ages`'s doc comment).
fn taken_leader_ages_mask(v: &Json, tag: &str) -> Result<u8, FixtureError> {
    let arr = req_arr(v, "taken_leader_ages", tag)?;
    let mut mask = 0u8;
    for item in arr {
        let s = item
            .as_str()
            .ok_or_else(|| FixtureError::new(format!("{tag}.taken_leader_ages: not a string")))?;
        mask |= 1 << (parse_age(s, tag)? as u8);
    }
    Ok(mask)
}

/// `p.pacts`: a list of `{name, owner, partner, a, b}` objects.
fn pacts_field(v: &Json, tag: &str) -> Result<PactList, FixtureError> {
    let arr = req_arr(v, "pacts", tag)?;
    let mut out = PactList::new();
    for (i, item) in arr.iter().enumerate() {
        let name = req_str(item, "name")?;
        let card = CardId::by_name(&name).ok_or_else(|| {
            FixtureError::new(format!("{tag}.pacts[{i}]: unknown card {name:?}"))
        })?;
        let owner = req_num(item, "owner")? as u8;
        let partner = req_num(item, "partner")? as u8;
        let a = req_num(item, "a")? as u8;
        let b = req_num(item, "b")? as u8;
        out.push(Pact { card, owner, partner, a, b });
    }
    Ok(out)
}

/// `p.war_declared_by_me`: `null` or `[name, attacker_idx, target_idx]`
/// (Python: `(name, p.idx, target)`, `engine/actions.py:1148`) ->
/// `(war_declared_by_me, war_target)`.
fn war_declared_by_me_field(v: &Json, tag: &str) -> Result<(CardId, u8), FixtureError> {
    match req(v, "war_declared_by_me")? {
        Json::Null => Ok((CardId::NONE, 0)),
        Json::Arr(a) if a.len() == 3 => {
            let name = a[0]
                .as_str()
                .ok_or_else(|| FixtureError::new(format!("{tag}.war_declared_by_me[0]: not a string")))?;
            let card = CardId::by_name(name).ok_or_else(|| {
                FixtureError::new(format!("{tag}.war_declared_by_me[0]: unknown card {name:?}"))
            })?;
            let target = a[2]
                .as_f64()
                .ok_or_else(|| FixtureError::new(format!("{tag}.war_declared_by_me[2]: not a number")))?
                as u8;
            Ok((card, target))
        }
        other => Err(FixtureError::new(format!(
            "{tag}.war_declared_by_me: expected null or a 3-element array, got {other:?}"
        ))),
    }
}

/// `p.wars_declared_on_me`: a list of `[name, attacker_idx, target_idx]`
/// (Python: `(name, p.idx, target)`, appended to the TARGET's
/// `wars_declared_on_me`, `engine/actions.py:1149`) -> the array `state.rs`
/// keys by attacker index instead (see the field's doc comment).
fn wars_declared_on_me_field(v: &Json, tag: &str) -> Result<[CardId; MAX_PLAYERS], FixtureError> {
    let arr = req_arr(v, "wars_declared_on_me", tag)?;
    let mut out = [CardId::NONE; MAX_PLAYERS];
    for (i, item) in arr.iter().enumerate() {
        let t = item
            .as_arr()
            .ok_or_else(|| FixtureError::new(format!("{tag}.wars_declared_on_me[{i}]: not an array")))?;
        let name = t
            .first()
            .and_then(Json::as_str)
            .ok_or_else(|| FixtureError::new(format!("{tag}.wars_declared_on_me[{i}][0]: not a string")))?;
        let attacker = t
            .get(1)
            .and_then(Json::as_f64)
            .ok_or_else(|| FixtureError::new(format!("{tag}.wars_declared_on_me[{i}][1]: not a number")))?
            as usize;
        let card = CardId::by_name(name).ok_or_else(|| {
            FixtureError::new(format!("{tag}.wars_declared_on_me[{i}][0]: unknown card {name:?}"))
        })?;
        if attacker >= MAX_PLAYERS {
            return Err(FixtureError::new(format!(
                "{tag}.wars_declared_on_me[{i}]: attacker index {attacker} out of range"
            )));
        }
        out[attacker] = card;
    }
    Ok(out)
}

/// A `PlayerState` with every field zeroed, for `GameState::players` slots
/// beyond `num_players` (Python's `players` list is exactly `num_players`
/// long; `state.rs`'s array is fixed at [`MAX_PLAYERS`]). Never read by
/// anything that respects `num_players` (`GameState::active`,
/// `legal_moves`, ...), so the exact values here do not matter -- only that
/// every field is a valid, in-range value.
fn blank_player(idx: u8) -> PlayerState {
    PlayerState {
        idx,
        techs: Tableau::new(),
        government: CardId::NONE,
        leader: CardId::NONE,
        used_leader_ability: false,
        wonder: CardId::NONE,
        wonder_steps: 0,
        completed_wonders: CardList::new(),
        destroyed_wonders: 0,
        homer_wonder: CardId::NONE,
        tactic: CardId::NONE,
        tactic_exclusive: false,
        colonies: CardList::new(),
        flipped_wonders: CardList::new(),
        taken_leader_ages: 0,
        war_declared_by_me: CardId::NONE,
        war_target: 0,
        wars_declared_on_me: [CardId::NONE; MAX_PLAYERS],
        pacts: PactList::new(),
        hand_civil: CardList::new(),
        hand_military: CardList::new(),
        hidden_civil: 0,
        hidden_military: 0,
        yellow_bank: 0,
        yellow_granted: 0,
        workers_free: 0,
        blue_total: 0,
        food: 0,
        resources: 0,
        science: 0,
        culture: 0,
        culture_rate_extra: 0,
        science_rate_extra: 0,
        strength_extra: 0,
        happy_extra: 0,
        civil_actions: 0,
        military_actions: 0,
        politics_done: false,
        tactic_action_used: false,
        taken_this_turn: CardList::new(),
        ca_spent_taking: 0,
        hammurabi_used: false,
        churchill_used: false,
        bach_upgrade_used: false,
        ocean_liners_used: false,
        caesar_double_politics_used: false,
        skip_next_politics: false,
        caesar_second_politics: false,
        peeked_event: CardId::NONE,
        ca_penalty_next_turn: 0,
        mil_discount: 0,
        mil_sci_discount: 0,
        one_time_discount: OneTimeDiscount::default(),
        resigned: false,
    }
}

fn load_player(v: &Json, idx: u8) -> Result<PlayerState, FixtureError> {
    let tag = format!("players[{idx}]");
    let json_idx = req_num(v, "idx")? as u8;
    if json_idx != idx {
        return Err(FixtureError::new(format!(
            "{tag}: idx field says {json_idx}, position in `players` says {idx}"
        )));
    }
    let (wonder, wonder_steps) = wonder_field(v, &tag)?;
    let (war_declared_by_me, war_target) = war_declared_by_me_field(v, &tag)?;
    Ok(PlayerState {
        idx,
        techs: techs_tableau(v, &tag)?,
        government: card_id_opt(req(v, "government")?, &format!("{tag}.government"))?,
        leader: card_id_opt(req(v, "leader")?, &format!("{tag}.leader"))?,
        used_leader_ability: req_bool(v, "used_leader_ability")?,
        wonder,
        wonder_steps,
        completed_wonders: card_list(v, "completed_wonders", &tag)?,
        destroyed_wonders: req_num(v, "destroyed_wonders")? as u8,
        homer_wonder: card_id_opt(req(v, "homer_wonder")?, &format!("{tag}.homer_wonder"))?,
        tactic: card_id_opt(req(v, "tactic")?, &format!("{tag}.tactic"))?,
        tactic_exclusive: req_bool(v, "tactic_exclusive")?,
        colonies: card_list(v, "colonies", &tag)?,
        flipped_wonders: card_list(v, "flipped_wonders", &tag)?,
        taken_leader_ages: taken_leader_ages_mask(v, &tag)?,
        war_declared_by_me,
        war_target,
        wars_declared_on_me: wars_declared_on_me_field(v, &tag)?,
        pacts: pacts_field(v, &tag)?,
        hand_civil: card_list(v, "hand_civil", &tag)?,
        hand_military: card_list(v, "hand_military", &tag)?,
        hidden_civil: req_num(v, "hidden_civil")? as u8,
        hidden_military: req_num(v, "hidden_military")? as u8,
        yellow_bank: req_num(v, "yellow_bank")? as u8,
        yellow_granted: req_num(v, "yellow_granted")? as u8,
        workers_free: req_num(v, "workers_free")? as u8,
        blue_total: req_num(v, "blue_total")? as u8,
        food: req_num(v, "food")? as u16,
        resources: req_num(v, "resources")? as u16,
        science: req_num(v, "science")? as u16,
        culture: req_num(v, "culture")? as u16,
        culture_rate_extra: req_num(v, "culture_rate_extra")? as i16,
        science_rate_extra: req_num(v, "science_rate_extra")? as i16,
        strength_extra: req_num(v, "strength_extra")? as i16,
        happy_extra: req_num(v, "happy_extra")? as i16,
        civil_actions: req_num(v, "civil_actions")? as i8,
        military_actions: req_num(v, "military_actions")? as i8,
        politics_done: req_bool(v, "politics_done")?,
        tactic_action_used: req_bool(v, "tactic_action_used")?,
        taken_this_turn: card_list(v, "taken_this_turn", &tag)?,
        ca_spent_taking: req_num(v, "ca_spent_taking")? as u8,
        hammurabi_used: req_bool(v, "hammurabi_used")?,
        churchill_used: req_bool(v, "churchill_used")?,
        bach_upgrade_used: req_bool(v, "bach_upgrade_used")?,
        ocean_liners_used: req_bool(v, "ocean_liners_used")?,
        caesar_double_politics_used: req_bool(v, "caesar_double_politics_used")?,
        skip_next_politics: req_bool(v, "skip_next_politics")?,
        caesar_second_politics: req_bool(v, "caesar_second_politics")?,
        peeked_event: card_id_opt(req(v, "peeked_event")?, &format!("{tag}.peeked_event"))?,
        ca_penalty_next_turn: req_num(v, "ca_penalty_next_turn")? as i8,
        mil_discount: req_num(v, "mil_discount")? as i16,
        mil_sci_discount: req_num(v, "mil_sci_discount")? as i16,
        one_time_discount: one_time_discount_field(v, &tag)?,
        resigned: req_bool(v, "resigned")?,
    })
}

/// `card_row`: exactly [`ROW_SIZE`] slots, each a name or `null`.
fn card_row_field(v: &Json) -> Result<[CardId; ROW_SIZE], FixtureError> {
    let arr = req_arr(v, "card_row", "state")?;
    if arr.len() != ROW_SIZE {
        return Err(FixtureError::new(format!(
            "state.card_row: {} slots, expected {ROW_SIZE}",
            arr.len()
        )));
    }
    let mut out = [CardId::NONE; ROW_SIZE];
    for (i, item) in arr.iter().enumerate() {
        out[i] = card_id_opt(item, &format!("state.card_row[{i}]"))?;
    }
    Ok(out)
}

/// One of the age-keyed dicts (`civil_discard`, `civil_removed`,
/// `discarded_military`): `{age_string: [names]}`, sparse (only ages that
/// have had a card land in them get a key). List order within one age is
/// preserved; key order is not meaningful (each key is read directly by
/// `Age`, never iterated).
fn age_keyed_lists(v: &Json, key: &str) -> Result<[CardList<MAX_DECK>; 5], FixtureError> {
    let mut out: [CardList<MAX_DECK>; 5] =
        [CardList::new(), CardList::new(), CardList::new(), CardList::new(), CardList::new()];
    let obj = match req(v, key)? {
        Json::Obj(fields) => fields,
        other => return Err(FixtureError::new(format!("state.{key}: not an object, got {other:?}"))),
    };
    for (age_str, list) in obj {
        let age = parse_age(age_str, &format!("state.{key}"))?;
        let arr = list
            .as_arr()
            .ok_or_else(|| FixtureError::new(format!("state.{key}[{age_str:?}]: not an array")))?;
        let mut cl = CardList::<MAX_DECK>::new();
        for (i, item) in arr.iter().enumerate() {
            let name = item.as_str().ok_or_else(|| {
                FixtureError::new(format!("state.{key}[{age_str:?}][{i}]: not a string"))
            })?;
            let id = CardId::by_name(name).ok_or_else(|| {
                FixtureError::new(format!("state.{key}[{age_str:?}][{i}]: unknown card {name:?}"))
            })?;
            cl.push(id);
        }
        out[age as usize] = cl;
    }
    Ok(out)
}

fn opt_u16(v: &Json, key: &str) -> Result<Option<u16>, FixtureError> {
    match v.get(key) {
        None | Some(Json::Null) => Ok(None),
        Some(other) => Ok(Some(
            other
                .as_f64()
                .ok_or_else(|| FixtureError::new(format!("{key}: not a number or null")))?
                as u16,
        )),
    }
}

fn opt_u8(v: &Json, key: &str) -> Result<Option<u8>, FixtureError> {
    match v.get(key) {
        None | Some(Json::Null) => Ok(None),
        Some(other) => Ok(Some(
            other
                .as_f64()
                .ok_or_else(|| FixtureError::new(format!("{key}: not a number or null")))?
                as u8,
        )),
    }
}

fn phase_field(v: &Json) -> Result<Phase, FixtureError> {
    match req_str(v, "phase")?.as_str() {
        "politics" => Ok(Phase::Politics),
        "actions" => Ok(Phase::Actions),
        "done" => Ok(Phase::Done),
        other => Err(FixtureError::new(format!("state.phase: unknown phase {other:?}"))),
    }
}

impl GameState {
    /// Load a `GameState.to_dict()` dump (one fixture ply's `"state"` field,
    /// or any other JSON value with the same shape) into a real `GameState`.
    ///
    /// See this module's section doc comment (just above) for the four
    /// Python fields this cannot represent and what happens to each.
    pub fn from_json(v: &Json) -> Result<GameState, FixtureError> {
        // `pending` / `queue` are LOADED now (see "the decision queue"
        // above); they used to be rejected, as was `one_time_discount`,
        // which is loaded now too. `seeded_by` is the one field still
        // dropped -- see this module's section doc comment for why it alone
        // is safe to drop.
        let num_players = req_num(v, "num_players")? as u8;
        if !(2..=MAX_PLAYERS as u8).contains(&num_players) {
            return Err(FixtureError::new(format!(
                "state.num_players: {num_players}, outside 2..={MAX_PLAYERS}"
            )));
        }
        let players_json = req_arr(v, "players", "state")?;
        if players_json.len() != num_players as usize {
            return Err(FixtureError::new(format!(
                "state.players: {} entries but num_players is {num_players}",
                players_json.len()
            )));
        }
        let mut players: [PlayerState; MAX_PLAYERS] =
            std::array::from_fn(|i| blank_player(i as u8));
        for (i, pv) in players_json.iter().enumerate() {
            players[i] = load_player(pv, i as u8)?;
        }

        Ok(GameState {
            num_players,
            seed: req_num(v, "seed")? as u64,
            players,
            current: req_num(v, "current")? as u8,
            turn: req_num(v, "turn")? as u16,
            round: req_num(v, "round")? as u16,
            start_player: req_num(v, "start_player")? as u8,
            age_civil: parse_age(&req_str(v, "age_civil")?, "state.age_civil")?,
            age_military: parse_age(&req_str(v, "age_military")?, "state.age_military")?,
            civil_deck: card_list(v, "civil_deck", "state")?,
            military_deck: card_list(v, "military_deck", "state")?,
            card_row: card_row_field(v)?,
            future_events: card_list(v, "future_events", "state")?,
            current_events: card_list(v, "current_events", "state")?,
            past_events: card_list(v, "past_events", "state")?,
            current_events_age: parse_age(&req_str(v, "current_events_age")?, "state.current_events_age")?,
            scoring_events: card_list(v, "scoring_events", "state")?,
            available_tactics: card_list(v, "available_tactics", "state")?,
            civil_discard: age_keyed_lists(v, "civil_discard")?,
            civil_removed: age_keyed_lists(v, "civil_removed")?,
            discarded_military: age_keyed_lists(v, "discarded_military")?,
            last_round: req_bool(v, "last_round")?,
            final_round_end: opt_u16(v, "final_round_end")?,
            game_over: req_bool(v, "game_over")?,
            phase: phase_field(v)?,
            forced_winner: opt_u8(v, "forced_winner")?,
            pending: pending_field(v)?,
            queue: queue_field(v)?,
        })
    }
}

// ======================================================= structural diff ==
//
// `tests/differential.rs`'s replay wants "state diverges at ply 41, field
// food" (`rust/DESIGN.md`, "How correctness is established"), not "digest
// mismatch". Computing a digest that would actually MATCH `tools/
// dump_fixtures.py::state_digest` byte-for-byte is not attainable anyway --
// that digest hashes Python's full `to_dict()`, including the three fields
// `GameState::from_json` above cannot represent, so a Rust digest could only
// ever agree with Python's by coincidence. A field-by-field structural
// compare between two ALREADY-LOADED `GameState`s is strictly more useful
// (it names the field) and sidesteps the mismatch entirely: it never looks
// at what Rust cannot represent, only at what it does.
//
// Reuses `GameState::from_json` as the parser for the "expected" side rather
// than comparing against raw `Json` -- one parser, checked against real
// games, rather than a second hand-rolled reader that could disagree with
// the first about what a field means.

impl GameState {
    /// Every difference between `self` and `other`, as `"path: detail"`
    /// strings -- empty means structurally identical over every field this
    /// type represents. Order-sensitive wherever the field itself is
    /// (DESIGN.md: "ordering is load-bearing all the way down into the
    /// containers"), scoped to `self.num_players` active players (the
    /// unused padding slots beyond that carry no information either state
    /// claims to have).
    pub fn diff(&self, other: &GameState) -> Vec<String> {
        let mut out = Vec::new();
        macro_rules! f {
            ($path:expr, $a:expr, $b:expr) => {
                if $a != $b {
                    out.push(format!("{}: {:?} != {:?}", $path, $a, $b));
                }
            };
        }
        f!("state.num_players", self.num_players, other.num_players);
        f!("state.seed", self.seed, other.seed);
        f!("state.current", self.current, other.current);
        f!("state.turn", self.turn, other.turn);
        f!("state.round", self.round, other.round);
        f!("state.start_player", self.start_player, other.start_player);
        f!("state.age_civil", self.age_civil, other.age_civil);
        f!("state.age_military", self.age_military, other.age_military);
        diff_cardlist(&mut out, "state.civil_deck", self.civil_deck.as_slice(), other.civil_deck.as_slice());
        diff_cardlist(
            &mut out,
            "state.military_deck",
            self.military_deck.as_slice(),
            other.military_deck.as_slice(),
        );
        f!("state.card_row", self.card_row, other.card_row);
        diff_cardlist(&mut out, "state.future_events", self.future_events.as_slice(), other.future_events.as_slice());
        diff_cardlist(&mut out, "state.current_events", self.current_events.as_slice(), other.current_events.as_slice());
        diff_cardlist(&mut out, "state.past_events", self.past_events.as_slice(), other.past_events.as_slice());
        f!("state.current_events_age", self.current_events_age, other.current_events_age);
        diff_cardlist(&mut out, "state.scoring_events", self.scoring_events.as_slice(), other.scoring_events.as_slice());
        diff_cardlist(
            &mut out,
            "state.available_tactics",
            self.available_tactics.as_slice(),
            other.available_tactics.as_slice(),
        );
        for age in 0..5 {
            diff_cardlist(
                &mut out,
                &format!("state.civil_discard[{age}]"),
                self.civil_discard[age].as_slice(),
                other.civil_discard[age].as_slice(),
            );
            diff_cardlist(
                &mut out,
                &format!("state.civil_removed[{age}]"),
                self.civil_removed[age].as_slice(),
                other.civil_removed[age].as_slice(),
            );
            diff_cardlist(
                &mut out,
                &format!("state.discarded_military[{age}]"),
                self.discarded_military[age].as_slice(),
                other.discarded_military[age].as_slice(),
            );
        }
        f!("state.last_round", self.last_round, other.last_round);
        f!("state.final_round_end", self.final_round_end, other.final_round_end);
        f!("state.game_over", self.game_over, other.game_over);
        f!("state.phase", self.phase, other.phase);
        f!("state.forced_winner", self.forced_winner, other.forced_winner);

        for i in 0..self.num_players.max(other.num_players) as usize {
            diff_player(&mut out, i, &self.players[i], &other.players[i]);
        }
        out
    }
}

fn diff_cardlist(out: &mut Vec<String>, path: &str, a: &[CardId], b: &[CardId]) {
    if a != b {
        out.push(format!("{path}: {a:?} != {b:?}"));
    }
}

fn diff_player(out: &mut Vec<String>, i: usize, a: &PlayerState, b: &PlayerState) {
    macro_rules! f {
        ($field:ident) => {
            if a.$field != b.$field {
                out.push(format!(
                    "state.players[{i}].{}: {:?} != {:?}",
                    stringify!($field),
                    a.$field,
                    b.$field
                ));
            }
        };
    }
    f!(idx);
    f!(government);
    f!(leader);
    f!(used_leader_ability);
    f!(wonder);
    f!(wonder_steps);
    f!(destroyed_wonders);
    f!(homer_wonder);
    f!(tactic);
    f!(tactic_exclusive);
    f!(taken_leader_ages);
    f!(war_declared_by_me);
    f!(war_target);
    f!(wars_declared_on_me);
    f!(hidden_civil);
    f!(hidden_military);
    f!(yellow_bank);
    f!(yellow_granted);
    f!(workers_free);
    f!(blue_total);
    f!(food);
    f!(resources);
    f!(science);
    f!(culture);
    f!(culture_rate_extra);
    f!(science_rate_extra);
    f!(strength_extra);
    f!(happy_extra);
    f!(civil_actions);
    f!(military_actions);
    f!(politics_done);
    f!(tactic_action_used);
    f!(ca_spent_taking);
    f!(hammurabi_used);
    f!(churchill_used);
    f!(bach_upgrade_used);
    f!(ocean_liners_used);
    f!(caesar_double_politics_used);
    f!(skip_next_politics);
    f!(caesar_second_politics);
    f!(peeked_event);
    f!(ca_penalty_next_turn);
    f!(mil_discount);
    f!(mil_sci_discount);
    f!(one_time_discount);
    f!(resigned);

    diff_cardlist(
        out,
        &format!("state.players[{i}].completed_wonders"),
        a.completed_wonders.as_slice(),
        b.completed_wonders.as_slice(),
    );
    diff_cardlist(out, &format!("state.players[{i}].colonies"), a.colonies.as_slice(), b.colonies.as_slice());
    diff_cardlist(
        out,
        &format!("state.players[{i}].flipped_wonders"),
        a.flipped_wonders.as_slice(),
        b.flipped_wonders.as_slice(),
    );
    diff_cardlist(out, &format!("state.players[{i}].hand_civil"), a.hand_civil.as_slice(), b.hand_civil.as_slice());
    diff_cardlist(
        out,
        &format!("state.players[{i}].hand_military"),
        a.hand_military.as_slice(),
        b.hand_military.as_slice(),
    );
    diff_cardlist(
        out,
        &format!("state.players[{i}].taken_this_turn"),
        a.taken_this_turn.as_slice(),
        b.taken_this_turn.as_slice(),
    );

    let ta: Vec<(CardId, TechSlot)> = a.techs.iter().map(|(id, s)| (id, *s)).collect();
    let tb: Vec<(CardId, TechSlot)> = b.techs.iter().map(|(id, s)| (id, *s)).collect();
    if ta != tb {
        out.push(format!("state.players[{i}].techs: {ta:?} != {tb:?}"));
    }

    let pa = a.pacts.as_slice();
    let pb = b.pacts.as_slice();
    if pa != pb {
        out.push(format!("state.players[{i}].pacts: {pa:?} != {pb:?}"));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn json_round_trips_the_shapes_fixtures_use() {
        let v = parse_json(r#"{"a": 1, "b": [1, 2.5, -3e2, true, false, null, "x\ny\"z"], "c": {}}"#)
            .unwrap();
        assert_eq!(v.get("a").unwrap().as_f64(), Some(1.0));
        let b = v.get("b").unwrap().as_arr().unwrap();
        assert_eq!(b[0].as_f64(), Some(1.0));
        assert_eq!(b[1].as_f64(), Some(2.5));
        assert_eq!(b[2].as_f64(), Some(-300.0));
        assert_eq!(b[3].as_bool(), Some(true));
        assert_eq!(b[4].as_bool(), Some(false));
        assert_eq!(b[5], Json::Null);
        assert_eq!(b[6].as_str(), Some("x\ny\"z"));
    }

    /// The exact payload `data/cards_military_actions.json`'s "Development
    /// of Civil Life" prints, as `tools/dump_fixtures.py` dumps it.
    #[test]
    fn one_time_discount_loads_the_only_payload_the_game_prints() {
        let v = parse_json(
            r#"{"one_time_discount": {"increasePopulation": {"food": 1},
                "build": {"resources": 1}, "developTechnology": {"science": 1}}}"#,
        )
        .unwrap();
        assert_eq!(
            one_time_discount_field(&v, "players[0]").unwrap(),
            OneTimeDiscount { build_resources: 1, develop_science: 1, pop_food: 1 }
        );
    }

    /// Absent (pre-event) and `{}` (dumped but empty) are both the zero
    /// discount, not an error -- most plies of most fixtures look like one
    /// of these two.
    #[test]
    fn one_time_discount_absent_or_empty_is_zero() {
        let empty = parse_json(r#"{"one_time_discount": {}}"#).unwrap();
        assert_eq!(one_time_discount_field(&empty, "p").unwrap(), OneTimeDiscount::default());
        let absent = parse_json(r#"{}"#).unwrap();
        assert_eq!(one_time_discount_field(&absent, "p").unwrap(), OneTimeDiscount::default());
    }

    /// A key this loader has no field for is an ERROR, not a silent zero: a
    /// dropped discount would make Rust overcharge for the rest of the
    /// replay and show up as a mystery cost divergence miles away.
    #[test]
    fn one_time_discount_rejects_a_key_it_cannot_represent() {
        let outer = parse_json(r#"{"one_time_discount": {"buildWonder": {"resources": 1}}}"#).unwrap();
        assert!(one_time_discount_field(&outer, "p").is_err(), "unknown outer key");
        let inner = parse_json(r#"{"one_time_discount": {"build": {"food": 1}}}"#).unwrap();
        assert!(one_time_discount_field(&inner, "p").is_err(), "unknown inner key");
        let shape = parse_json(r#"{"one_time_discount": {"build": 1}}"#).unwrap();
        assert!(one_time_discount_field(&shape, "p").is_err(), "not an object");
    }

    #[test]
    fn parse_move_maps_every_known_tag() {
        let take = parse_json(r#"["take", 3]"#).unwrap();
        assert_eq!(parse_move(&take).unwrap(), Move::Take { slot: 3 });

        let end_turn = parse_json(r#"["end_turn"]"#).unwrap();
        assert_eq!(parse_move(&end_turn).unwrap(), Move::EndTurn);

        let remove_leader_yellow = parse_json(r#"["remove_leader_yellow"]"#).unwrap();
        assert_eq!(parse_move(&remove_leader_yellow).unwrap(), Move::RemoveLeaderYellow);

        let bronze = CardId::by_name("Bronze").expect("Bronze must exist for this test to mean anything");
        let iron = CardId::by_name("Iron").expect("Iron must exist for this test to mean anything");
        let up = parse_json(r#"["upgrade", "Bronze", "Iron"]"#).unwrap();
        assert_eq!(parse_move(&up).unwrap(), Move::Upgrade { from: bronze, to: iron });

        let warriors = CardId::by_name("Warriors").expect("Warriors must exist for this test to mean anything");
        let barbarossa = parse_json(r#"["barbarossa", "Warriors"]"#).unwrap();
        assert_eq!(parse_move(&barbarossa).unwrap(), Move::Barbarossa { card: warriors });

        let theology = CardId::by_name("Theology").expect("Theology must exist for this test to mean anything");
        let drama = CardId::by_name("Drama").expect("Drama must exist for this test to mean anything");
        let bach = parse_json(r#"["bach_theater", "Theology", "Drama"]"#).unwrap();
        assert_eq!(parse_move(&bach).unwrap(), Move::BachTheater { from: theology, to: drama });

        let send_discard = parse_json(r#"["send_discard", "Warriors"]"#).unwrap();
        assert_eq!(parse_move(&send_discard).unwrap(), Move::SendDiscard { card: warriors });
    }

    #[test]
    fn parse_move_rejects_unknown_tag() {
        let v = parse_json(r#"["not_a_real_move", 1]"#).unwrap();
        assert!(parse_move(&v).is_err());
    }

    #[test]
    fn parse_move_rejects_unknown_card() {
        let v = parse_json(r#"["build", "Not A Real Card"]"#).unwrap();
        assert!(parse_move(&v).is_err());
    }

    /// `GameState::from_json` against a real dumped state: loads without
    /// error, round-trips (`diff` against itself is empty), and -- the whole
    /// point of the `_FILE_JSON_KW` fix -- the tableau is NOT alphabetically
    /// sorted (a real game builds `Warriors` before `Agriculture` at this
    /// seed; alphabetical would put `Agriculture` first).
    #[test]
    fn from_json_loads_a_real_fixture_state_and_round_trips() {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/3p_seed1.jsonl");
        let records = read_fixture_file(&path).expect("read 3p_seed1.jsonl");
        let ply10 = records
            .iter()
            .find_map(|r| match r {
                Record::Ply(p) if p.ply == 10 => p.state.as_ref(),
                _ => None,
            })
            .expect("ply 10 must carry a state snapshot at state_every=10");
        let state = GameState::from_json(ply10).expect("from_json");
        assert_eq!(state.num_players, 3);
        let techs: Vec<&str> = state.players[0].techs.iter().map(|(id, _)| id.name()).collect();
        assert_eq!(techs, vec!["Warriors", "Agriculture", "Bronze", "Philosophy", "Religion"]);
        assert!(state.diff(&state).is_empty(), "a state must not differ from itself");

        let reloaded = GameState::from_json(ply10).unwrap();
        assert!(state.diff(&reloaded).is_empty(), "reloading the same JSON must produce an equal state");
    }
}
