//! A bit-exact port of CPython's `random.Random`, restricted to the sliver
//! the engine actually uses: construct from an `int` seed, then `shuffle`.
//!
//! DESIGN.md rule 3/4 applies here too even though this isn't `GameState`:
//! the Mersenne Twister state is `[u32; 624]` inline, never a `Vec`, and
//! there is no dependency on the `rand` crate. The whole point of this file
//! is that Rust and Python must draw the identical sequence of words for the
//! identical seed, so "equivalent" RNG algorithms are useless here -- only
//! the literal MT19937 reference algorithm CPython embeds will do.
//!
//! Call sites this exists for (do not add more surface than these need):
//!   engine/economy.py:258,263  `_random.Random(state.seed * 7919 + state.turn).shuffle(...)`
//!   engine/events.py:155       `rng.shuffle(deck)`
//!   engine/game.py:47,57,81,90,176,179,428  `random.Random(<int>)` then `.shuffle(...)`
//!
//! Only `getrandbits` and `_randbelow` are implemented, because `shuffle` is
//! defined in terms of them -- not `random()`, `sample`, `choice`, `randint`,
//! `gauss`, or anything else CPython's `random` module offers.
//!
//! Verified against CPython 3.13.7 (`/Library/Frameworks/Python.framework/
//! Versions/3.13/lib/python3.13/random.py`, read directly, plus the C
//! `_random.Random` core it wraps -- `_randommodule.c`'s `init_by_array`,
//! `init_genrand` and `genrand_uint32`, which have not changed since Python
//! 2 because they ARE the 2002 Matsumoto/Nishimura `mt19937ar.c` reference
//! implementation). Confirmed empirically too: `tests::matches_cpython_exactly`
//! below replays a table of (seed, length, permutation) triples generated by
//! running the real interpreter -- see the comment on `FIXTURES`.

use crate::cards::CardId;

const N: usize = 624;
const M: usize = 397;
const MATRIX_A: u32 = 0x9908_b0df;
const UPPER_MASK: u32 = 0x8000_0000;
const LOWER_MASK: u32 = 0x7fff_ffff;

/// A CPython-compatible MT19937 stream.
#[derive(Clone)]
pub struct PyRandom {
    state: [u32; N],
    /// Position of the next untempered word to hand out. `>= N` forces a
    /// twist before the next draw, mirroring CPython's `self->index`.
    index: usize,
}

impl PyRandom {
    /// Equivalent to `random.Random(seed)` for an `int` seed.
    ///
    /// CPython's C-level `random_seed` (`_randommodule.c`) takes
    /// `PyNumber_Absolute(seed)` for an int seed BEFORE splitting it into
    /// 32-bit limbs -- a negative seed is seeded identically to its positive
    /// magnitude.
    ///
    /// Width is `i128`, not `i64`: every call site folds a `u64` game seed
    /// through a couple of small fixed multipliers (`state.seed * 1_000_003`
    /// in `game::rng_for`, `state.seed * 7919` in `economy::deck_rng`) plus
    /// tiny `u16` turn/round offsets, which tops out around 84 bits of
    /// magnitude (`u64::MAX` is 64 bits, `1_000_003` is 20). `i128` has 127
    /// bits of magnitude, so there are ~43 bits -- about 13 decimal orders of
    /// magnitude -- of permanent headroom: the ceiling is fixed by
    /// `state.seed`'s type (`u64`) and these constants being compile-time
    /// literals, not by anything that grows at runtime (a long-running climb
    /// generation counter included -- it is folded into `state.seed` via
    /// `u64` wrapping arithmetic before it ever reaches here, so it is
    /// already capped at `u64::MAX`). `i64` was tried first and is what
    /// overflowed in production (see `game::rng_for`'s doc comment); widen
    /// again rather than silently truncating if a call site ever needs a key
    /// bigger than a `u64` times a `u32`-ish constant.
    pub fn new(seed: i128) -> Self {
        let n: u128 = seed.unsigned_abs();

        // `init_by_array`'s key is `n` split into little-endian 32-bit
        // limbs, sized as `ceil(bit_length(n) / 32)` -- EXCEPT a zero seed,
        // which CPython still keys with a single zero limb rather than an
        // empty key (`_randommodule.c`: `keyused = bits == 0 ? 1 : ...`).
        // `n.leading_zeros()` is 128 for `n == 0`, so `bits` is naturally 0
        // and the `keyused` formula below falls out without a special case.
        //
        // Four 32-bit limbs cover the full 128-bit magnitude range (this is
        // the generalization of the old two-limb, `i64`-only version -- for
        // any `n` that fits in 64 bits, `keyused` is still at most 2 and
        // `key[0..2]` is filled identically, so already-representable seeds
        // draw byte-identical streams to before this widening).
        let bits = 128 - n.leading_zeros() as usize;
        let keyused = if bits == 0 { 1 } else { (bits - 1) / 32 + 1 };
        let mut key = [0u32; 4];
        for (i, limb) in key.iter_mut().enumerate().take(keyused) {
            *limb = (n >> (32 * i)) as u32;
        }

        let mut rng = PyRandom { state: [0; N], index: N };
        rng.init_by_array(&key[..keyused]);
        rng
    }

    /// `mt19937ar.c`'s `init_genrand`: the scalar seeding CPython uses only
    /// as the fixed starting point for `init_by_array` below, never on its
    /// own (an `int` seed always goes through `init_by_array`, even a
    /// single-word one).
    fn init_genrand(&mut self, s: u32) {
        self.state[0] = s;
        for i in 1..N {
            self.state[i] = (1_812_433_253u32)
                .wrapping_mul(self.state[i - 1] ^ (self.state[i - 1] >> 30))
                .wrapping_add(i as u32);
        }
        self.index = N;
    }

    /// `mt19937ar.c`'s `init_by_array`, byte-for-byte -- this is the piece
    /// that is easy to get "algorithmically right, numerically wrong" by
    /// reaching for the simpler scalar `init_genrand` instead. CPython's
    /// `int` seeding NEVER uses scalar seeding directly.
    fn init_by_array(&mut self, key: &[u32]) {
        self.init_genrand(19_650_218);
        let key_length = key.len();
        let mut i = 1usize;
        let mut j = 0usize;
        let mut k = N.max(key_length);
        while k > 0 {
            self.state[i] = (self.state[i]
                ^ (self.state[i - 1] ^ (self.state[i - 1] >> 30)).wrapping_mul(1_664_525))
            .wrapping_add(key[j])
            .wrapping_add(j as u32);
            i += 1;
            j += 1;
            if i >= N {
                self.state[0] = self.state[N - 1];
                i = 1;
            }
            if j >= key_length {
                j = 0;
            }
            k -= 1;
        }
        k = N - 1;
        while k > 0 {
            self.state[i] = (self.state[i]
                ^ (self.state[i - 1] ^ (self.state[i - 1] >> 30)).wrapping_mul(1_566_083_941))
            .wrapping_sub(i as u32);
            i += 1;
            if i >= N {
                self.state[0] = self.state[N - 1];
                i = 1;
            }
            k -= 1;
        }
        self.state[0] = 0x8000_0000;
    }

    /// `mt19937ar.c`'s `genrand_uint32`: twist the full state once every 624
    /// draws, then temper. This is the only place new randomness enters the
    /// stream; `getrandbits` is purely a consumer of it.
    fn genrand_uint32(&mut self) -> u32 {
        if self.index >= N {
            const MAG01: [u32; 2] = [0, MATRIX_A];
            for kk in 0..N - M {
                let y = (self.state[kk] & UPPER_MASK) | (self.state[kk + 1] & LOWER_MASK);
                self.state[kk] = self.state[kk + M] ^ (y >> 1) ^ MAG01[(y & 1) as usize];
            }
            for kk in N - M..N - 1 {
                let y = (self.state[kk] & UPPER_MASK) | (self.state[kk + 1] & LOWER_MASK);
                self.state[kk] = self.state[kk + M - N] ^ (y >> 1) ^ MAG01[(y & 1) as usize];
            }
            let y = (self.state[N - 1] & UPPER_MASK) | (self.state[0] & LOWER_MASK);
            self.state[N - 1] = self.state[M - 1] ^ (y >> 1) ^ MAG01[(y & 1) as usize];
            self.index = 0;
        }
        let y = self.state[self.index];
        self.index += 1;
        let y = y ^ (y >> 11);
        let y = y ^ ((y << 7) & 0x9d2c_5680);
        let y = y ^ ((y << 15) & 0xefc6_0000);
        y ^ (y >> 18)
    }

    /// `getrandbits(k)` for `1 <= k <= 32`: CPython's `random_getrandbits`
    /// fast path (`genrand_uint32() >> (32 - k)`), which is the ONLY path
    /// `shuffle` can reach through this engine.
    ///
    /// The multi-word path (`k > 32`, assembling several `genrand_uint32`
    /// draws little-endian) exists in CPython for `getrandbits` on huge `k`,
    /// but `shuffle`'s `k` is `n.bit_length()` where `n <= len(deck) + 1`.
    /// The engine's largest sequence is `state::MAX_DECK == 64`
    /// (`bit_length` 7); reaching `k > 32` would need a sequence longer than
    /// 2**32 elements, which cannot exist in memory. It is therefore
    /// intentionally NOT implemented -- panicking here is a signal that
    /// something is being shuffled far outside what this port was checked
    /// against, not a case to silently paper over.
    fn getrandbits(&mut self, k: u32) -> u32 {
        assert!((1..=32).contains(&k), "getrandbits({k}): only 1..=32 is implemented (see comment)");
        self.genrand_uint32() >> (32 - k)
    }

    /// `_randbelow_with_getrandbits` (`Lib/random.py`), the only `_randbelow`
    /// CPython's `Random` uses once `getrandbits` exists (see
    /// `__init_subclass__` in `random.py`, which picks it over the
    /// `random()`-based fallback precisely because `_random.Random` defines
    /// `getrandbits`).
    ///
    /// The rejection loop is load-bearing: every rejected draw still
    /// consumes a `genrand_uint32` word, so replacing this with a modulo
    /// (`genrand_uint32() % n`) would desynchronise the stream from the
    /// first rejection onward -- silently, since it still returns *a*
    /// value in range, just not the SAME one Python drew next.
    /// `random.random()` -- CPython's `random_random`: a 53-bit float in
    /// `[0, 1)`, assembled from two tempered words as
    /// `(a * 2**26 + b) / 2**53` with `a = w >> 5` and `b = w >> 6`.
    ///
    /// Nothing in the ENGINE draws a float -- shuffling is `randbelow` all the
    /// way down -- so this exists for the search side (`climb`'s mutation
    /// operators), where the alternative was a second, unrelated random number
    /// generator in the same process. Two streams that both look random and
    /// have to stay separately seeded is a state-management problem with no
    /// upside; one stream, one seed, one twist schedule.
    pub fn random(&mut self) -> f64 {
        let a = (self.genrand_uint32() >> 5) as f64;
        let b = (self.genrand_uint32() >> 6) as f64;
        (a * 67_108_864.0 + b) * (1.0 / 9_007_199_254_740_992.0)
    }

    fn randbelow(&mut self, n: u64) -> u64 {
        debug_assert!(n > 0, "_randbelow is only defined for n > 0");
        let k = 64 - n.leading_zeros(); // n.bit_length()
        let mut r = self.getrandbits(k) as u64;
        while r >= n {
            r = self.getrandbits(k) as u64;
        }
        r
    }
}

/// `random.Random.shuffle` (CPython 3.11+; `Lib/random.py`), Fisher-Yates
/// walking DOWN from the end:
///
/// ```python
/// for i in reversed(range(1, len(x))):
///     j = randbelow(i + 1)
///     x[i], x[j] = x[j], x[i]
/// ```
///
/// `range(1, len(x))` is empty for `len(x) <= 1`, so a 0- or 1-element slice
/// draws NOTHING from the stream -- there is no explicit early return to
/// port, the loop bound already is one. That matters for callers chaining
/// multiple `rng.shuffle(...)` calls on the same `Random` (as `game.py`
/// does): getting this boundary wrong desyncs every draw after it.
pub fn shuffle_cards(rng: &mut PyRandom, cards: &mut [CardId]) {
    for i in (1..cards.len()).rev() {
        let j = rng.randbelow((i + 1) as u64) as usize;
        cards.swap(i, j);
    }
}

/// A [`PyRandom`] whose seeding is deferred until the first draw.
///
/// `game::rng_for`'s three callers (`deal_row`, `resume_end_turn`,
/// `after_resign`) each build a stream "just in case" a reshuffle happens
/// somewhere downstream (`deal` -> `advance_age`, gated on the civil/military
/// deck actually running dry -- a rare event, once or twice an age, not once
/// a call). A live `sample` profile of a `plan` bot at width=8 found
/// `PyRandom::new` at the top of the named symbols, ahead of every scoring
/// function; a call-count check confirmed why: of ~510k `PyRandom::new`
/// calls across 8 games, `game::rng_for` alone made 99.66% of them, and the
/// deck-empty branch that would actually consume a word is hit on only a
/// small fraction of those. Every one of those calls was paying MT19937's
/// full `init_by_array` (~1900 word-mixes) for a stream nothing ever read
/// from.
///
/// This type changes NONE of that: the seed formula and the MT19937
/// algorithm are untouched (both are checked bit-exact against recorded
/// CPython fixtures -- see `game.rs`'s "Randomness" doc comment -- and
/// nothing here may diverge from that), it only moves the expensive part of
/// [`PyRandom::new`] from "every call" to "every call that ends up shuffling
/// something." A chain that DOES shuffle more than once (an age boundary
/// inside `deal`, say) still draws from a single continuing stream, exactly
/// as an eagerly-built `PyRandom` threaded through the same calls always
/// has -- [`get`](Self::get) builds the stream at most once and hands out
/// the same instance on every later call.
pub struct LazyRandom {
    seed: i128,
    inner: Option<PyRandom>,
}

impl LazyRandom {
    pub fn new(seed: i128) -> Self {
        LazyRandom { seed, inner: None }
    }

    /// Wrap an already-built stream (e.g. one `new_game` setup has already
    /// drawn words from for an earlier, unconditional shuffle) so a later
    /// call that only MIGHT need more words -- `deal`'s `advance_age`
    /// branch, say -- continues the SAME stream rather than starting a
    /// second one from word 0 at the same seed.
    pub fn built(rng: PyRandom) -> Self {
        LazyRandom { seed: 0, inner: Some(rng) }
    }

    /// The real `PyRandom`, built on first use and reused after that.
    pub fn get(&mut self) -> &mut PyRandom {
        self.inner.get_or_insert_with(|| PyRandom::new(self.seed))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// (seed, expected permutation of `0..len`) triples, `len` implied by
    /// the slice length. Generated by shuffling `list(range(len))` under
    /// real CPython 3.13.7 for a spread of seeds (zero, small, negative,
    /// values that straddle the 32-bit and 64-bit limb boundary, and the
    /// exact shapes the engine constructs: `seed*1000003+turn*97+round`,
    /// `seed*7919+turn`, `seed^0x5EED`) and lengths (0, 1, 2, 3, 5, 13, 50,
    /// 64 -- 64 is `state::MAX_DECK`, the largest sequence this engine ever
    /// shuffles). Regenerate with `/private/tmp/gen_rng_fixtures.py` if
    /// CPython's algorithm ever changes (it hasn't since Python 2).
    #[rustfmt::skip]
    const FIXTURES: &[(i64, &[u16])] = &[
        (0, &[]),
        (0, &[0]),
        (0, &[0, 1]),
        (0, &[0, 2, 1]),
        (0, &[2, 1, 0, 4, 3]),
        (0, &[1, 10, 9, 5, 11, 2, 3, 7, 8, 4, 0, 12, 6]),
        (0, &[43, 1, 28, 14, 36, 12, 0, 27, 47, 7, 33, 34, 20, 49, 5, 38, 11, 23, 40, 15, 10, 21, 46, 3, 9, 4, 41, 42, 39, 17, 29, 45, 6, 35, 18, 8, 44, 13, 37, 22, 30, 19, 25, 31, 32, 16, 2, 26, 48, 24]),
        (0, &[29, 28, 24, 33, 35, 60, 23, 40, 11, 27, 61, 3, 5, 7, 42, 45, 12, 59, 0, 55, 1, 44, 41, 14, 15, 17, 47, 20, 63, 10, 62, 54, 36, 51, 21, 4, 43, 52, 9, 38, 34, 58, 39, 6, 46, 18, 8, 57, 13, 37, 22, 30, 19, 53, 50, 25, 31, 32, 16, 2, 26, 56, 48, 49]),
        (1, &[]),
        (1, &[0]),
        (1, &[1, 0]),
        (1, &[1, 2, 0]),
        (1, &[2, 3, 4, 0, 1]),
        (1, &[8, 12, 0, 11, 5, 3, 6, 7, 10, 4, 1, 9, 2]),
        (1, &[2, 15, 47, 9, 21, 29, 48, 5, 46, 14, 11, 32, 34, 26, 49, 19, 39, 38, 12, 22, 37, 20, 42, 35, 33, 10, 3, 18, 45, 25, 23, 17, 43, 0, 27, 40, 1, 44, 6, 13, 24, 41, 30, 28, 31, 7, 16, 4, 36, 8]),
        (1, &[22, 12, 52, 3, 19, 5, 60, 58, 2, 33, 10, 8, 29, 26, 25, 9, 44, 18, 62, 11, 47, 40, 15, 39, 56, 57, 32, 23, 49, 43, 21, 45, 42, 34, 35, 46, 20, 61, 37, 14, 63, 53, 0, 38, 27, 50, 1, 55, 6, 13, 24, 41, 30, 28, 59, 31, 7, 16, 4, 48, 51, 54, 36, 17]),
        (2, &[]),
        (2, &[0]),
        (2, &[1, 0]),
        (2, &[1, 2, 0]),
        (2, &[2, 1, 3, 4, 0]),
        (2, &[9, 3, 6, 12, 10, 7, 8, 4, 2, 5, 11, 1, 0]),
        (2, &[24, 33, 49, 35, 6, 15, 4, 22, 9, 29, 34, 21, 18, 39, 26, 20, 7, 43, 17, 47, 30, 40, 12, 36, 14, 11, 0, 1, 31, 8, 44, 28, 46, 32, 25, 27, 45, 37, 2, 41, 13, 38, 16, 19, 42, 10, 23, 48, 5, 3]),
        (2, &[3, 21, 39, 49, 15, 55, 9, 18, 30, 6, 22, 35, 14, 59, 8, 11, 44, 4, 31, 45, 24, 0, 33, 63, 26, 36, 61, 52, 50, 12, 57, 20, 29, 46, 1, 48, 17, 41, 28, 34, 60, 32, 25, 40, 27, 58, 43, 37, 2, 56, 13, 38, 16, 19, 54, 42, 51, 47, 10, 53, 23, 62, 5, 7]),
        (-1, &[]),
        (-1, &[0]),
        (-1, &[1, 0]),
        (-1, &[1, 2, 0]),
        (-1, &[2, 3, 4, 0, 1]),
        (-1, &[8, 12, 0, 11, 5, 3, 6, 7, 10, 4, 1, 9, 2]),
        (-1, &[2, 15, 47, 9, 21, 29, 48, 5, 46, 14, 11, 32, 34, 26, 49, 19, 39, 38, 12, 22, 37, 20, 42, 35, 33, 10, 3, 18, 45, 25, 23, 17, 43, 0, 27, 40, 1, 44, 6, 13, 24, 41, 30, 28, 31, 7, 16, 4, 36, 8]),
        (-1, &[22, 12, 52, 3, 19, 5, 60, 58, 2, 33, 10, 8, 29, 26, 25, 9, 44, 18, 62, 11, 47, 40, 15, 39, 56, 57, 32, 23, 49, 43, 21, 45, 42, 34, 35, 46, 20, 61, 37, 14, 63, 53, 0, 38, 27, 50, 1, 55, 6, 13, 24, 41, 30, 28, 59, 31, 7, 16, 4, 48, 51, 54, 36, 17]),
        (-5, &[]),
        (-5, &[0]),
        (-5, &[0, 1]),
        (-5, &[0, 1, 2]),
        (-5, &[0, 1, 3, 2, 4]),
        (-5, &[2, 3, 11, 10, 12, 1, 6, 7, 0, 8, 5, 4, 9]),
        (-5, &[11, 18, 9, 37, 28, 26, 42, 46, 48, 38, 21, 45, 49, 31, 27, 35, 17, 20, 14, 19, 4, 2, 25, 12, 43, 5, 8, 13, 32, 36, 0, 34, 6, 24, 40, 30, 23, 7, 10, 3, 15, 29, 1, 33, 41, 44, 22, 47, 16, 39]),
        (-5, &[18, 61, 54, 59, 20, 12, 46, 38, 28, 39, 55, 31, 8, 48, 16, 9, 51, 5, 52, 40, 21, 37, 45, 27, 14, 35, 19, 4, 2, 25, 63, 57, 42, 11, 17, 26, 13, 0, 43, 36, 6, 34, 24, 60, 30, 23, 7, 10, 3, 56, 15, 49, 29, 58, 1, 33, 41, 62, 53, 44, 50, 22, 47, 32]),
        (42, &[]),
        (42, &[0]),
        (42, &[1, 0]),
        (42, &[1, 0, 2]),
        (42, &[3, 1, 2, 4, 0]),
        (42, &[7, 6, 2, 9, 12, 5, 11, 8, 3, 4, 0, 1, 10]),
        (42, &[25, 23, 19, 11, 4, 45, 26, 9, 29, 16, 31, 21, 12, 3, 39, 38, 10, 24, 35, 0, 43, 18, 33, 48, 41, 30, 28, 20, 22, 42, 46, 36, 32, 44, 13, 49, 47, 2, 27, 37, 5, 34, 6, 8, 14, 15, 17, 1, 7, 40]),
        (42, &[23, 25, 7, 22, 45, 33, 19, 59, 46, 9, 40, 18, 42, 31, 16, 21, 36, 41, 29, 20, 11, 50, 39, 48, 3, 30, 24, 55, 4, 57, 54, 49, 10, 0, 60, 28, 44, 26, 52, 12, 35, 53, 38, 32, 58, 13, 51, 62, 2, 27, 37, 5, 34, 56, 43, 6, 61, 8, 63, 15, 17, 47, 1, 14]),
        (7919, &[]),
        (7919, &[0]),
        (7919, &[0, 1]),
        (7919, &[0, 1, 2]),
        (7919, &[0, 2, 4, 1, 3]),
        (7919, &[1, 9, 4, 3, 12, 8, 0, 6, 11, 5, 2, 7, 10]),
        (7919, &[9, 26, 33, 43, 41, 32, 46, 12, 14, 37, 30, 44, 2, 39, 6, 13, 49, 18, 4, 8, 36, 10, 19, 45, 42, 23, 48, 47, 1, 16, 28, 17, 5, 21, 24, 7, 38, 15, 34, 35, 25, 20, 0, 3, 27, 29, 22, 11, 31, 40]),
        (7919, &[9, 12, 38, 10, 26, 46, 58, 18, 14, 6, 51, 37, 62, 30, 2, 31, 19, 36, 42, 45, 41, 13, 50, 16, 52, 4, 8, 28, 59, 55, 60, 54, 32, 1, 44, 23, 56, 40, 17, 5, 33, 21, 24, 7, 48, 15, 39, 47, 34, 49, 35, 43, 25, 20, 53, 0, 3, 27, 29, 22, 57, 11, 61, 63]),
        (12345, &[]),
        (12345, &[0]),
        (12345, &[0, 1]),
        (12345, &[2, 0, 1]),
        (12345, &[4, 2, 1, 0, 3]),
        (12345, &[12, 10, 8, 1, 7, 9, 2, 3, 5, 4, 0, 11, 6]),
        (12345, &[1, 24, 44, 25, 3, 9, 38, 43, 32, 49, 15, 21, 28, 33, 8, 37, 48, 14, 47, 20, 40, 29, 2, 6, 4, 31, 30, 18, 13, 39, 42, 5, 22, 34, 11, 35, 16, 41, 7, 45, 10, 27, 36, 17, 12, 23, 19, 0, 46, 26]),
        (12345, &[56, 63, 48, 57, 44, 8, 31, 15, 21, 2, 42, 25, 1, 30, 24, 3, 37, 18, 38, 20, 49, 41, 62, 29, 47, 14, 61, 28, 34, 59, 6, 4, 13, 9, 50, 32, 26, 33, 5, 22, 43, 45, 39, 11, 40, 35, 16, 58, 7, 55, 10, 27, 36, 17, 12, 23, 54, 19, 51, 60, 52, 0, 46, 53]),
        (999999999, &[]),
        (999999999, &[0]),
        (999999999, &[0, 1]),
        (999999999, &[2, 0, 1]),
        (999999999, &[4, 1, 3, 0, 2]),
        (999999999, &[11, 5, 9, 3, 10, 7, 0, 12, 8, 6, 2, 1, 4]),
        (999999999, &[11, 47, 1, 33, 13, 14, 5, 15, 43, 2, 9, 20, 28, 41, 36, 46, 12, 40, 0, 19, 44, 42, 37, 26, 34, 18, 6, 22, 30, 23, 8, 31, 25, 27, 21, 48, 38, 45, 35, 3, 29, 49, 39, 4, 17, 32, 24, 10, 7, 16]),
        (999999999, &[49, 11, 23, 2, 5, 19, 43, 53, 41, 26, 20, 9, 15, 60, 0, 61, 45, 46, 30, 52, 28, 33, 22, 6, 8, 56, 18, 12, 42, 50, 14, 37, 44, 38, 1, 34, 48, 55, 47, 36, 13, 58, 54, 31, 25, 27, 21, 40, 62, 51, 59, 35, 3, 29, 16, 39, 4, 57, 17, 63, 24, 10, 7, 32]),
        (2147483647, &[]),
        (2147483647, &[0]),
        (2147483647, &[0, 1]),
        (2147483647, &[2, 0, 1]),
        (2147483647, &[4, 1, 3, 0, 2]),
        (2147483647, &[2, 10, 7, 8, 11, 9, 6, 0, 12, 4, 3, 1, 5]),
        (2147483647, &[8, 46, 5, 4, 32, 16, 14, 10, 17, 35, 30, 11, 27, 31, 29, 24, 39, 42, 19, 25, 49, 6, 2, 48, 37, 43, 41, 36, 22, 15, 26, 3, 40, 38, 1, 23, 44, 28, 33, 13, 9, 47, 34, 0, 21, 45, 18, 12, 7, 20]),
        (2147483647, &[17, 8, 58, 57, 10, 42, 16, 26, 61, 36, 11, 5, 19, 47, 29, 46, 14, 22, 51, 60, 4, 30, 49, 32, 27, 24, 37, 54, 20, 6, 2, 15, 38, 25, 31, 3, 53, 48, 1, 35, 23, 41, 44, 39, 43, 63, 55, 28, 33, 13, 9, 62, 34, 50, 0, 21, 45, 56, 18, 12, 7, 52, 59, 40]),
        (4294967296, &[]),
        (4294967296, &[0]),
        (4294967296, &[1, 0]),
        (4294967296, &[2, 1, 0]),
        (4294967296, &[3, 4, 1, 2, 0]),
        (4294967296, &[12, 2, 7, 8, 3, 4, 10, 11, 9, 0, 6, 5, 1]),
        (4294967296, &[49, 47, 13, 14, 35, 19, 45, 25, 10, 15, 12, 6, 40, 33, 2, 36, 18, 23, 16, 11, 44, 17, 38, 37, 9, 42, 3, 48, 41, 31, 5, 29, 30, 24, 43, 20, 32, 27, 4, 8, 0, 28, 34, 21, 39, 46, 1, 26, 22, 7]),
        (4294967296, &[41, 36, 16, 44, 61, 6, 40, 33, 47, 42, 3, 25, 15, 18, 45, 13, 63, 43, 2, 5, 57, 37, 55, 52, 31, 58, 23, 12, 50, 38, 54, 11, 9, 46, 62, 17, 35, 49, 19, 7, 10, 29, 30, 24, 53, 20, 32, 27, 4, 8, 0, 28, 34, 21, 48, 51, 56, 39, 60, 1, 59, 26, 22, 14]),
        (4294967303, &[]),
        (4294967303, &[0]),
        (4294967303, &[1, 0]),
        (4294967303, &[2, 1, 0]),
        (4294967303, &[3, 0, 4, 2, 1]),
        (4294967303, &[12, 10, 1, 8, 2, 4, 7, 9, 6, 0, 11, 5, 3]),
        (4294967303, &[49, 33, 6, 31, 0, 44, 19, 9, 17, 23, 12, 26, 30, 7, 34, 11, 43, 39, 10, 35, 42, 13, 32, 1, 2, 36, 28, 15, 40, 46, 20, 25, 29, 8, 18, 16, 27, 5, 37, 47, 38, 4, 45, 41, 24, 3, 21, 22, 48, 14]),
        (4294967303, &[33, 12, 47, 56, 0, 52, 44, 19, 36, 39, 50, 1, 62, 40, 46, 23, 9, 45, 57, 17, 34, 15, 54, 6, 63, 32, 14, 20, 55, 35, 13, 60, 7, 26, 2, 53, 30, 11, 31, 10, 25, 29, 8, 18, 16, 27, 5, 42, 43, 37, 61, 49, 38, 4, 58, 59, 41, 24, 3, 51, 21, 22, 48, 28]),
        (1099511627776, &[]),
        (1099511627776, &[0]),
        (1099511627776, &[1, 0]),
        (1099511627776, &[2, 1, 0]),
        (1099511627776, &[1, 4, 3, 2, 0]),
        (1099511627776, &[11, 9, 2, 7, 4, 8, 3, 0, 6, 12, 10, 5, 1]),
        (1099511627776, &[19, 33, 34, 0, 30, 10, 5, 9, 36, 7, 28, 44, 37, 39, 8, 21, 15, 38, 16, 14, 13, 32, 48, 18, 29, 45, 12, 49, 23, 1, 11, 31, 26, 2, 17, 43, 20, 41, 47, 46, 35, 40, 25, 24, 3, 27, 4, 42, 22, 6]),
        (1099511627776, &[61, 10, 48, 52, 18, 1, 28, 33, 0, 21, 39, 5, 62, 53, 19, 34, 11, 41, 36, 15, 6, 47, 46, 9, 14, 59, 7, 58, 8, 16, 32, 30, 37, 29, 51, 38, 55, 12, 50, 63, 49, 23, 31, 26, 2, 17, 57, 20, 54, 44, 56, 43, 45, 60, 35, 40, 25, 24, 3, 27, 4, 42, 22, 13]),
        (9223372036854775807, &[]),
        (9223372036854775807, &[0]),
        (9223372036854775807, &[0, 1]),
        (9223372036854775807, &[2, 0, 1]),
        (9223372036854775807, &[0, 4, 3, 1, 2]),
        (9223372036854775807, &[12, 1, 6, 9, 4, 3, 0, 8, 7, 2, 11, 10, 5]),
        (9223372036854775807, &[28, 33, 47, 0, 44, 9, 46, 18, 49, 22, 35, 1, 21, 36, 48, 4, 16, 11, 41, 19, 2, 32, 27, 38, 15, 12, 13, 45, 24, 26, 5, 25, 39, 14, 3, 7, 34, 43, 23, 10, 17, 37, 30, 6, 29, 31, 8, 40, 42, 20]),
        (9223372036854775807, &[57, 9, 28, 33, 0, 52, 18, 58, 27, 1, 60, 20, 24, 13, 5, 12, 22, 15, 43, 41, 62, 36, 4, 32, 16, 50, 11, 48, 19, 2, 38, 21, 44, 55, 59, 26, 46, 25, 35, 54, 14, 3, 7, 61, 34, 56, 39, 23, 53, 10, 17, 37, 47, 45, 49, 30, 6, 29, 31, 51, 8, 63, 42, 40]),
        (12345040918, &[]),
        (12345040918, &[0]),
        (12345040918, &[0, 1]),
        (12345040918, &[0, 2, 1]),
        (12345040918, &[0, 3, 1, 4, 2]),
        (12345040918, &[8, 1, 9, 11, 3, 6, 0, 7, 2, 10, 12, 4, 5]),
        (12345040918, &[4, 34, 41, 33, 24, 45, 37, 27, 38, 10, 22, 5, 25, 44, 8, 26, 32, 36, 2, 7, 46, 14, 35, 13, 48, 21, 15, 12, 19, 16, 42, 3, 17, 49, 29, 9, 40, 0, 31, 39, 28, 6, 1, 30, 11, 43, 47, 20, 18, 23]),
        (12345040918, &[12, 37, 16, 21, 57, 4, 48, 32, 8, 44, 27, 58, 49, 2, 13, 55, 54, 25, 34, 36, 10, 53, 38, 41, 15, 46, 60, 35, 22, 7, 62, 5, 14, 63, 19, 26, 56, 24, 33, 40, 3, 17, 23, 29, 9, 42, 59, 51, 0, 31, 39, 28, 45, 52, 6, 1, 30, 50, 11, 43, 61, 20, 18, 47]),
        (7911098, &[]),
        (7911098, &[0]),
        (7911098, &[0, 1]),
        (7911098, &[0, 1, 2]),
        (7911098, &[4, 0, 1, 3, 2]),
        (7911098, &[6, 1, 12, 10, 3, 9, 0, 8, 2, 5, 7, 4, 11]),
        (7911098, &[1, 6, 46, 19, 3, 29, 30, 7, 0, 12, 24, 25, 20, 47, 32, 26, 13, 42, 15, 14, 18, 23, 45, 43, 39, 11, 5, 2, 40, 37, 8, 10, 27, 38, 48, 35, 21, 34, 17, 36, 28, 4, 49, 33, 9, 41, 22, 31, 16, 44]),
        (7911098, &[12, 46, 15, 38, 24, 6, 8, 2, 23, 7, 3, 59, 49, 43, 29, 40, 1, 14, 0, 19, 52, 18, 39, 63, 30, 5, 25, 13, 20, 37, 26, 62, 50, 54, 60, 11, 53, 56, 44, 10, 27, 42, 55, 51, 16, 35, 21, 34, 17, 36, 28, 61, 45, 4, 58, 47, 33, 57, 9, 41, 22, 48, 31, 32]),
        (113837, &[]),
        (113837, &[0]),
        (113837, &[0, 1]),
        (113837, &[0, 1, 2]),
        (113837, &[2, 1, 0, 3, 4]),
        (113837, &[1, 11, 0, 10, 8, 3, 5, 12, 4, 7, 2, 6, 9]),
        (113837, &[29, 34, 18, 7, 11, 35, 4, 6, 21, 47, 37, 10, 1, 38, 44, 42, 26, 20, 16, 33, 36, 15, 41, 3, 8, 24, 13, 48, 19, 0, 25, 14, 30, 23, 22, 12, 32, 2, 5, 45, 49, 43, 28, 40, 46, 17, 31, 9, 27, 39]),
        (113837, &[50, 49, 15, 1, 11, 29, 8, 48, 19, 44, 21, 7, 62, 33, 41, 57, 24, 58, 45, 46, 27, 4, 63, 25, 10, 3, 43, 35, 20, 13, 18, 16, 36, 37, 47, 34, 6, 60, 26, 38, 0, 14, 30, 23, 22, 12, 32, 42, 54, 53, 2, 5, 59, 39, 56, 28, 40, 61, 51, 17, 52, 31, 9, 55]),
        (24301, &[]),
        (24301, &[0]),
        (24301, &[1, 0]),
        (24301, &[2, 1, 0]),
        (24301, &[2, 4, 0, 3, 1]),
        (24301, &[0, 11, 5, 1, 8, 4, 12, 7, 10, 3, 6, 9, 2]),
        (24301, &[10, 18, 2, 33, 49, 0, 17, 32, 13, 31, 27, 46, 5, 15, 16, 6, 40, 28, 42, 1, 7, 20, 34, 4, 45, 24, 8, 23, 35, 43, 11, 3, 38, 21, 29, 36, 25, 44, 14, 22, 48, 19, 30, 41, 47, 37, 12, 26, 39, 9]),
        (24301, &[31, 27, 2, 13, 5, 24, 15, 0, 23, 34, 63, 33, 36, 4, 32, 62, 10, 59, 35, 6, 45, 44, 53, 28, 8, 11, 1, 7, 20, 51, 56, 9, 17, 16, 49, 3, 47, 21, 29, 42, 25, 38, 43, 40, 58, 57, 46, 14, 22, 48, 50, 61, 19, 30, 41, 60, 52, 55, 37, 12, 26, 39, 54, 18]),
    ];

    #[test]
    fn matches_cpython_exactly() {
        for &(seed, expected) in FIXTURES {
            let n = expected.len();
            let mut cards: Vec<CardId> = (0..n as u16).map(CardId).collect();
            let mut rng = PyRandom::new(i128::from(seed));
            shuffle_cards(&mut rng, &mut cards);
            let got: Vec<u16> = cards.iter().map(|c| c.0).collect();
            assert_eq!(got, expected, "seed={seed} len={n}");
        }
    }

    #[test]
    fn zero_and_one_length_consume_nothing() {
        // len<=1 must not touch the stream: two independent RNGs seeded the
        // same must still agree on the NEXT draw after shuffling a 0- or
        // 1-element slice, matching `range(1, len(x))` being empty.
        let mut a = PyRandom::new(123);
        let mut b = PyRandom::new(123);
        let mut empty: [CardId; 0] = [];
        let mut one = [CardId(0)];
        shuffle_cards(&mut a, &mut empty);
        shuffle_cards(&mut a, &mut one);
        assert_eq!(a.genrand_uint32(), b.genrand_uint32());
    }

    #[test]
    fn same_seed_reproduces() {
        let mut a = PyRandom::new(2026);
        let mut b = PyRandom::new(2026);
        let mut xs: Vec<CardId> = (0..20u16).map(CardId).collect();
        let mut ys = xs.clone();
        shuffle_cards(&mut a, &mut xs);
        shuffle_cards(&mut b, &mut ys);
        assert_eq!(xs.iter().map(|c| c.0).collect::<Vec<_>>(), ys.iter().map(|c| c.0).collect::<Vec<_>>());
    }

    // ------------------------------------------------------------ LazyRandom

    /// Deferring `PyRandom::new` to the first actual draw must not change
    /// what gets drawn: a `LazyRandom` and an eagerly-built `PyRandom`
    /// seeded identically shuffle the same deck the same way. This is the
    /// property the whole fix rests on -- `game::rng_for`'s callers used to
    /// pay MT19937's full init on every call whether or not anything was
    /// ever shuffled; `LazyRandom` only changes WHEN the stream is built,
    /// never the seed formula or the algorithm, so this must hold for every
    /// caller's fixture bytes to stay unchanged.
    #[test]
    fn a_lazy_random_shuffles_identically_to_an_eager_one_seeded_the_same() {
        let seed = 987_654_321;
        let mut eager = PyRandom::new(seed);
        let mut lazy = LazyRandom::new(seed);

        let mut xs: Vec<CardId> = (0..30u16).map(CardId).collect();
        let mut ys = xs.clone();
        shuffle_cards(&mut eager, &mut xs);
        shuffle_cards(lazy.get(), &mut ys);
        assert_eq!(
            xs.iter().map(|c| c.0).collect::<Vec<_>>(),
            ys.iter().map(|c| c.0).collect::<Vec<_>>(),
            "a lazily-built stream must draw the identical sequence as an eager one at the same seed"
        );
    }

    /// A chain that calls [`LazyRandom::get`] more than once (mirroring
    /// `advance_age` shuffling the civil deck and then the military deck
    /// from the SAME stream) must keep drawing forward, not rebuild a fresh
    /// stream at the same seed on the second call -- that would replay the
    /// first shuffle's words instead of continuing past them, exactly the
    /// "two shuffles must share one stream" invariant `game.rs`'s own
    /// "Randomness" doc comment already requires of the eager code this
    /// replaces.
    #[test]
    fn repeated_get_calls_keep_drawing_from_the_same_stream_not_a_fresh_one() {
        let seed = 42;
        let mut eager = PyRandom::new(seed);
        let mut lazy = LazyRandom::new(seed);

        let mut a1: Vec<CardId> = (0..13u16).map(CardId).collect();
        let mut a2 = a1.clone();
        shuffle_cards(&mut eager, &mut a1);
        shuffle_cards(lazy.get(), &mut a2); // first `get`: builds the stream
        assert_eq!(a1.iter().map(|c| c.0).collect::<Vec<_>>(), a2.iter().map(|c| c.0).collect::<Vec<_>>());

        let mut b1: Vec<CardId> = (0..13u16).map(CardId).collect();
        let mut b2 = b1.clone();
        shuffle_cards(&mut eager, &mut b1); // continues the SAME eager stream
        shuffle_cards(lazy.get(), &mut b2); // second `get`: must reuse, not rebuild
        assert_eq!(
            b1.iter().map(|c| c.0).collect::<Vec<_>>(),
            b2.iter().map(|c| c.0).collect::<Vec<_>>(),
            "a second `get()` must continue the stream built by the first, not restart it"
        );
    }

    /// A different seed must determinize differently -- the property that
    /// makes root determinization meaningful at all (a search that always
    /// drew the same "random" deck order would not be sampling anything).
    /// Two different seeds shuffling the same 64-card deck (this port's
    /// largest, `state::MAX_DECK`) landing on the identical permutation
    /// would be an astronomically unlikely coincidence, not a bug this test
    /// should tolerate silently, so a plain inequality is the right check.
    #[test]
    fn different_seeds_give_different_shuffles() {
        let mut a = LazyRandom::new(1);
        let mut b = LazyRandom::new(2);
        let mut xs: Vec<CardId> = (0..64u16).map(CardId).collect();
        let mut ys = xs.clone();
        shuffle_cards(a.get(), &mut xs);
        shuffle_cards(b.get(), &mut ys);
        assert_ne!(xs, ys, "different seeds must not determinize to the same order");
    }

    /// `LazyRandom::built` wraps an already-drawn-from stream (`new_game`'s
    /// own use: two unconditional shuffles happen before `deal` is called,
    /// and `deal`'s possible `advance_age` must continue THAT stream, not
    /// restart a fresh one at word 0). Constructing it from a `PyRandom`
    /// that has already produced output and then drawing once more must
    /// match drawing one more time from that same original `PyRandom`
    /// directly.
    #[test]
    fn built_wraps_an_already_advanced_stream_without_restarting_it() {
        let mut original = PyRandom::new(7);
        let _ = original.genrand_uint32(); // advance it past word 0
        let next_from_original = original.genrand_uint32();

        let mut replay = PyRandom::new(7);
        let _ = replay.genrand_uint32(); // advance identically
        let mut built = LazyRandom::built(replay);
        assert_eq!(
            built.get().genrand_uint32(),
            next_from_original,
            "built() must continue the wrapped stream, not reseed it"
        );
    }

    /// The widening pin: `PyRandom::new` used to take `i64`; the key-limb
    /// loop it now uses (`i128`, up to four 32-bit limbs) is a
    /// generalization that must fill `key[0..2]` identically to the old
    /// hardcoded two-limb version for any seed that fit in the old range.
    /// `12345` is an ordinary small seed well inside that range (it is also
    /// one of `FIXTURES`' seeds, but this test checks the RAW MT19937 words
    /// directly rather than a shuffle outcome, so a bug that only showed up
    /// after the words `shuffle` never reads cannot hide from it). The
    /// expected words below were captured from this same widened
    /// implementation and cross-checked against `matches_cpython_exactly`'s
    /// CPython-derived fixture for seed 12345, which shuffles from the same
    /// stream -- so this is not just "whatever the code prints today", it is
    /// anchored to real CPython output one call removed.
    #[test]
    fn a_small_seed_within_the_old_i64_range_still_draws_the_same_raw_words_after_the_i128_widening(
    ) {
        let mut rng = PyRandom::new(12345i128);
        let words: Vec<u32> = (0..6).map(|_| rng.genrand_uint32()).collect();
        assert_eq!(
            words,
            vec![1_789_368_711, 3_146_859_322, 43_676_229, 3_522_623_596, 3_544_234_957, 3_448_207_591],
            "a small seed's raw MT19937 word stream must not change just because \
             PyRandom::new's parameter widened from i64 to i128"
        );
    }
}
