//! `engine/bots/weighted.py` lines 1730-3211: card, hand and wonder pricing --
//! what a card in hand or a wonder in progress is worth, board-aware.
//!
//! This file owns only the YIELD-PLUMBING layer: turning one card's printed
//! numbers into `(feature, amount, kind)` triples and summing them at a
//! weight vector. The VALUATION layer built on top -- `action_value`,
//! `tech_value`, `gov_value`, `card_potential`, `_hand_total`, `_swap_slot`,
//! `hand_potential`, `wonder_potential`, `_gains_only`, `tactic_terms`,
//! `hand_mil_potential`, `rival_hand_potential` -- is a separate port and
//! lives elsewhere; nothing below decides what a hand or a wonder is worth,
//! only what one card is.
//!
//! ## The type system already fixed the bug this file exists to prevent
//!
//! Python's `_card_yields` walks `card.get("effects") or {}` -- a raw
//! `dict[str, Any]` -- against two hand-maintained lookup tables
//! (`_EFF_TO_FEATURE`, `_PROD_TO_FEATURE`), plus a top-level-field special
//! case for units and a per-block special case for territories. The entire
//! second half of the Python module's own doc comments (`DELIBERATELY_UNPRICED`
//! and every test in `tests/test_card_pricing.py`) exists to catch a key
//! silently falling through that walk -- `culture`/`science` on ten wonders
//! did, for most of the project's life, because nothing failed when they did.
//!
//! `crate::cards::CardEffects` (generated by `tools/gen_cards.py` from the
//! same underlying data) already closes that hole a level down: every
//! recurring effect key is a named, typed field, and a key `gen_cards.py`
//! cannot classify stops the BUILD, not a test run days or months later. So
//! this file reads typed fields (`card.effects.culture`, `card.effects
//! .strength`, ...) instead of walking a dict, and the Python tables
//! (`_PROD_TO_FEATURE`/`_EFF_TO_FEATURE`/`_TERR_TO_FEATURE`/
//! `_UNIT_TO_FEATURE`/`_BONUS_TO_FEATURE`) collapse into the `match`/`if`
//! structure of [`card_yields`] below -- there is no dict to keep in sync
//! with a card table that no longer exists as a dict either.
//!
//! One consequence worth flagging explicitly: `gen_cards.py` FUSES several
//! Python dict keys that mean different things into the SAME typed field,
//! because they feed the same `Stats` slot in `effects.rs`:
//!
//! * `CardEffects.strength` is Python's top-level `card["strength"]` on a
//!   unit card (per-worker rate), a genuine `effects.strength` key on
//!   everything else, AND the top-level `strength` a TACTIC also prints
//!   (`effects.tacticBonus`'s duplicate spelling, DELIBERATELY_UNPRICED
//!   bucket 5) -- three different meanings sharing one field. [`card_yields`]
//!   dispatches on [`crate::cards::CardType::is_unit`] first (unit ->
//!   `YieldKind::Unit`), skips `CardType::Tactic` entirely (never priced,
//!   matching Python), and prices everything else as a flat gain.
//! * `CardEffects.strength`/`.happy`/`.civil_actions`/`.military_actions`/
//!   `.blue_tokens`/`.yellow_tokens` are ALSO where a territory's
//!   `permanentEffects` land (a territory's own `effects` dict is `{}` in
//!   the source data -- see the Python source's own note on `_TERR_TO_FEATURE`
//!   for why that is not a coincidence: `deferred_credit`, the auction path,
//!   prices the identical two blocks). [`card_yields`] dispatches on
//!   `CardType::Territory` before reading any of these six fields, so a
//!   territory's flat numbers are priced through `territory_credit`
//!   (`YieldKind::Territory`) and never double-counted as a bare gain.
//! * `CardEffects.civil_actions`/`.military_actions` are ALSO where a
//!   GOVERNMENT's top-level action counts land (RULES_SPEC 8.1) -- Python's
//!   `_card_yields` never reads these for a government (they are top-level
//!   fields on the Python card dict, not inside `effects`; see
//!   `tests/test_card_pricing.py`'s `TOP_LEVEL_UNPRICED["civilActions"]`).
//!   [`card_yields`] skips both fields for `CardType::Government`, leaving a
//!   government's action counts to the valuation layer's `gov_value` (which
//!   reads them board-aware, through `board_yields::government_plans`).
//!
//! `effects.free_civil_action` and `effects.on_build_culture` are dead
//! fields (always `0` on every one of the 236 base-game cards): the
//! `freeCivilAction`/`onBuildCulture` keys are STRINGS/booleans in the
//! source data (which action, not how many; whether, not how much), so
//! `gen_cards.py` routes them through [`crate::cards::Special`] instead --
//! `Special::FreeCivilAction` (a presence flag, matching Python's
//! `_EFF_SPECIAL["freeCivilAction"]` treatment exactly) and
//! `Special::OnBuildCulture` (board-priced, `board_yields.rs`'s concern, not
//! this file's -- Python's own `_card_yields` never prices it either).
//!
//! ## API the valuation layer calls
//!
//! * [`card_yields`]/[`card_choice`]/[`sum_yields`] -- the pricing table
//!   itself. [`card_yields`] pushes into a caller-supplied `&mut Vec`
//!   (DESIGN.md rule 4: this is called for every card in every hand on every
//!   evaluation, so the caller owns one scratch buffer across the whole
//!   evaluation and clears it between cards rather than each call
//!   allocating). [`card_choice`] is `Option<(CardYield, CardYield)>`, not a
//!   `Vec` of alternatives -- today's only mutually-exclusive card (Reserves,
//!   `Special::GainFoodOrResources`, "N food OR N resources") is exactly a
//!   pair, and a hypothetical wider choice should widen the return type, not
//!   grow a `Vec` next to it.
//! * [`board_credit_key`]/[`swap_type`] -- board-pricing plumbing
//!   (`card_board_*` offsets, `SINGLE_SLOT`).
//! * [`yield_marginal`] -- `_yield_marginal`: [`rivals::feature_marginal`]
//!   plus the two ring-fenced pseudo-features (`resource_discount`/
//!   `restricted_resources`). `rivals.rs` landed (with `feature_marginal`)
//!   while this file was being written, so this calls it directly rather
//!   than through an injected closure -- DESIGN.md's "no DI for its own
//!   sake" rule only excuses a closure for a dependency that is genuinely
//!   not ported yet, and by the time this file was done, that dependency
//!   was. Note the mismatched index width this exposes: `rivals::
//!   feature_marginal` takes `idx: u8` where `board_yields.rs`'s functions
//!   ([`card_yields`]'s neighbours in the valuation layer) take `idx: usize`
//!   -- two sibling ports picked different conventions independently. Not
//!   this file's to fix (out of this pass's line range); flagged here and in
//!   the port report so the valuation layer, which will call both, does not
//!   have to rediscover it.
//! * [`crate::cards::CardType::is_unit`]/[`crate::bots::board_yields::
//!   is_levelled_type`]/[`crate::cards::CardType::is_action`]/
//!   [`crate::cards::CardType::is_government`] -- `_is_unit`/
//!   `_is_levelled_tech`/`_is_action`/`_is_government`. These are exhaustive
//!   `CardType` predicates, not functions of a card NAME, so they live on
//!   `CardType` itself (`is_unit`/`is_action`/`is_government`, the first two
//!   already ported this way for `board_yields.rs`; `is_action`/
//!   `is_government` added alongside this file) or, for `is_levelled_tech`,
//!   on `board_yields::is_levelled_type` where the sibling `is_swap_type`/
//!   `is_single_slot` predicates already live. There is no wrapper of the
//!   same name in this module -- a caller writes `id.kind().is_unit()`, not
//!   `cards::is_unit(id)`.
//! * [`DELIBERATELY_UNPRICED`]/[`UNPRICED_VALUES`] -- the documented gap, see
//!   their own doc comments below.

use crate::bots::board_yields;
use crate::cards::{CardId, CardType, Special};
use crate::state::GameState;

use super::rivals;
use super::weights::WeightKey;
use super::weights::Weights;

// ------------------------------------------------------------------ triples

/// The third slot of a yield triple -- mirrors Python's `_Y_GAIN`/`_Y_COST`/
/// `_Y_RATE`/`_Y_UNIT`/`_Y_TERR`/`_Y_BONUS` (plain `int` constants there,
/// because `_sum_yields` is the only reader and a bare `int` was enough to
/// switch on). A real enum here for the same reason [`super::weights::
/// WeightKey`] is one instead of a string: [`sum_yields`]'s `match` below is
/// exhaustive, so a seventh kind added later is a compile error at every
/// place that needs to know how to price it, not a silent `else` branch.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum YieldKind {
    /// Priced straight through `w[key]` -- one-shot gains and permanent
    /// modifiers printed on the card.
    Gain,
    /// Priced through `max(0.0, w[key])` -- `science`/`resource_stock` are
    /// STOCK weights a hill climb is free to drive negative (the 4p champion
    /// reached `science = -6.09`), and paying a cost must never read as a
    /// gain because of it.
    Cost,
    /// The short `culture`/`science` spelling (a wonder's per-turn rate,
    /// docs/CARD_BLINDNESS.md's headline omission) -- scaled by
    /// `card_rate_credit`, resolved once by [`sum_yields`]'s caller and
    /// threaded through as the `credit` argument, so the A/B against the
    /// pre-fix pricing is one knob.
    Rate,
    /// A military unit's per-worker `strength` (the top-level field a
    /// worker's `production` block never held) -- scaled by
    /// `unit_strength_credit`.
    Unit,
    /// A territory's `immediateEffects`/`permanentEffects` -- scaled by
    /// `territory_credit`.
    Territory,
    /// A Military Bonus card's defence/colonization numbers -- scaled by
    /// `bonus_card_credit`.
    Bonus,
}

/// `(feature, amount, kind)` -- what one line of a card's printed data is
/// worth, before a weight vector prices it. `WeightKey`, not a board-yields
/// [`crate::bots::board_yields::Feature`]: every triple here is fed straight
/// into `w.get(key)` ([`sum_yields`]) or, for the two ring-fenced pseudo-
/// features, into `feature_marginal` ([`yield_marginal`]) -- the same
/// weight-vector namespace `evaluate` itself indexes, not the narrower
/// swap-diff vocabulary `board_yields.rs` emits.
pub type CardYield = (WeightKey, f64, YieldKind);

/// Push `(key, amount, kind)` if `amount` is nonzero. Python's `_card_yields`
/// appends every triple it finds unconditionally (a zero-valued production
/// entry never appears in the printed data in the first place, so the two
/// are equivalent in practice); skipping a zero here is a cheap early-out on
/// [`crate::cards::CARDS`]'s otherwise mostly-zero `CardEffects` structs, not
/// a behaviour change -- [`sum_yields`]'s own `if amt != 0.0` guard would
/// have discarded it anyway.
#[inline]
fn push(out: &mut Vec<CardYield>, key: WeightKey, amount: i32, kind: YieldKind) {
    if amount != 0 {
        out.push((key, amount as f64, kind));
    }
}

// -------------------------------------------------------------- card_yields

/// `_card_yields`: every `(feature, amount, kind)` triple `name` prints,
/// independent of weights or board -- a pure function of card identity.
///
/// Pushes into `out` rather than returning a fresh `Vec` (DESIGN.md rule 4:
/// this runs for every card in every hand on every 1-ply candidate, so the
/// caller owns one scratch buffer for a whole evaluation and clears it
/// between cards -- `out.clear()` is the caller's job, not this function's,
/// so a caller that wants to ACCUMULATE across several cards can).
///
/// Python `lru_cache`s this per card name forever, because `C.db().by_name
/// .get(name)` is a dict lookup on a cold path relative to the rest of
/// evaluation. There is no dict here to cache the result of walking --
/// [`CardId::get`] is an array index into a `'static` table, and the work
/// below is a fixed handful of field reads and comparisons, cheaper than the
/// `HashMap` Python's cache itself would cost in Rust (DESIGN.md rule 1: no
/// process-global mutable cache). Recomputed on every call, matching
/// `horizon.rs`'s and `board_yields.rs`'s own "no memo cache" precedent.
pub fn card_yields(id: CardId, out: &mut Vec<CardYield>) {
    let card = id.get();
    let kind = card.kind;
    let eff = &card.effects;
    let prod = &card.production;

    // `_PROD_TO_FEATURE`: printed per-worker yield, always a flat gain --
    // farms/mines/urban buildings' `production` block, scaled by workers
    // elsewhere (`effects.rs`), priced here at its FACE value (one worker).
    push(out, WeightKey::CultureRate, prod.culture as i32, YieldKind::Gain);
    push(out, WeightKey::ScienceRate, prod.science as i32, YieldKind::Gain);
    push(out, WeightKey::FoodRate, prod.food as i32, YieldKind::Gain);
    push(out, WeightKey::ResourceRate, prod.resources as i32, YieldKind::Gain);
    push(out, WeightKey::HappyMargin, prod.happy as i32, YieldKind::Gain);
    push(out, WeightKey::Strength, prod.strength as i32, YieldKind::Gain);

    // `_UNIT_TO_FEATURE`: a military unit's per-worker STRENGTH, printed at
    // the card's top level in Python (never in `production`) and folded into
    // `effects.strength` here -- see this module's top doc comment. Ten
    // cards; all ten priced as pure cost before this bucket existed
    // (docs/CARD_BLINDNESS.md).
    if kind.is_unit() {
        push(out, WeightKey::Strength, eff.strength as i32, YieldKind::Unit);
    }

    if kind == CardType::Territory {
        // `_TERR_TO_FEATURE`: a territory's `immediateEffects` (one-shot,
        // paid the moment the colony is claimed) and `permanentEffects`
        // (ongoing) -- both fused into `effects`/`immediate_effects` on the
        // Rust side (see this module's top doc comment), both credited
        // through `territory_credit` so the pre-fix pricing (0.0 for every
        // territory) is one knob away. Every field below is the exhaustive
        // set the live 12 territory cards ever set (census, 2026-08-05):
        // `permanentEffects` never prints `civilActions`/`militaryActions`/
        // `food`/`resources`/`cultureProduction`/`scienceProduction` today,
        // only `strength`/`happiness`/`yellowTokens`/`blueTokens` -- but
        // every field is read regardless, exactly as Python's block walk
        // would read whichever keys a future territory printed.
        push(out, WeightKey::Strength, eff.strength as i32, YieldKind::Territory);
        // `happy`/`happiness` -> `happy_margin`, NOT the bare `happy` weight
        // (which does not exist) -- the one substitution `_TERR_TO_FEATURE`
        // makes on top of `_YIELD_TO_FEATURE`, and it is required: `features
        // ()` resolves `happy` by hand into `happy_margin` and nothing else
        // ever reads a `"happy"` coordinate.
        push(out, WeightKey::HappyMargin, eff.happy as i32, YieldKind::Territory);
        push(out, WeightKey::CivilActions, eff.civil_actions as i32, YieldKind::Territory);
        push(out, WeightKey::MilitaryActions, eff.military_actions as i32, YieldKind::Territory);
        push(out, WeightKey::YellowBank, eff.yellow_tokens as i32, YieldKind::Territory);
        push(out, WeightKey::BlueFree, eff.blue_tokens as i32, YieldKind::Territory);

        let imm = &card.immediate_effects;
        push(out, WeightKey::FoodStock, imm.food as i32, YieldKind::Territory);
        push(out, WeightKey::ResourceStock, imm.resources as i32, YieldKind::Territory);
        push(out, WeightKey::Culture, imm.culture as i32, YieldKind::Territory);
        push(out, WeightKey::Science, imm.science as i32, YieldKind::Territory);
        push(out, WeightKey::FreeWorkers, imm.population as i32, YieldKind::Territory);
        push(out, WeightKey::HandMilitary, imm.draw_military_cards as i32, YieldKind::Territory);
    } else {
        // `_EFF_TO_FEATURE`: the general `effects` block. A territory's own
        // `effects` dict is `{}` in the source data (everything it prints
        // lives in the two blocks above), so this whole branch is exactly
        // Python's "the general loop finds nothing on a territory" --
        // structural here rather than incidental.
        push(out, WeightKey::Culture, eff.gain_culture as i32, YieldKind::Gain);
        push(out, WeightKey::Science, eff.gain_science as i32, YieldKind::Gain);
        push(out, WeightKey::FoodStock, eff.gain_food as i32, YieldKind::Gain);
        push(out, WeightKey::ResourceStock, eff.gain_resources as i32, YieldKind::Gain);

        // `civilActions`/`militaryActions`: a genuine per-card grant on
        // every type EXCEPT a government, whose own action counts land in
        // these same two fields but are never read by `_card_yields` in
        // Python (top-level fields there; `gov_value`'s board-aware job) --
        // see this module's top doc comment.
        if kind != CardType::Government {
            push(out, WeightKey::CivilActions, eff.civil_actions as i32, YieldKind::Gain);
            push(out, WeightKey::MilitaryActions, eff.military_actions as i32, YieldKind::Gain);
        }

        // the short `culture`/`science` spelling: per-turn RATE gains,
        // separated from the flat-gain bucket only so `card_rate_credit` can
        // switch them off and recover the exact pre-fix (silently dropped)
        // pricing for the A/B -- docs/CARD_BLINDNESS.md's headline fix.
        push(out, WeightKey::CultureRate, eff.culture as i32, YieldKind::Rate);
        push(out, WeightKey::ScienceRate, eff.science as i32, YieldKind::Rate);

        // `strength`: skip entirely for a Tactic, and skip here for a unit
        // (already priced above as `YieldKind::Unit` -- pushing it again
        // here would double-count the exact same field). A tactic's
        // top-level `strength` (its per-army bonus) is folded into this same
        // field -- see this module's top doc comment -- but it is
        // DELIBERATELY UNPRICED: `effects.tacticBonus`/`tacticBonusObsolete`
        // are a duplicate spelling of it, board-scaled (armies you can
        // FORM), and priced instead by `tactic_gain`/`tactic_short` off
        // `effects::tactic_outlook` (the valuation layer, not this file).
        // Every other type's `effects.strength` (special-tech, wonder,
        // leader) is a genuine flat gain.
        if kind != CardType::Tactic && !kind.is_unit() {
            push(out, WeightKey::Strength, eff.strength as i32, YieldKind::Gain);
        }
        push(out, WeightKey::HappyMargin, eff.happy as i32, YieldKind::Gain);
        push(out, WeightKey::YellowBank, eff.yellow_tokens as i32, YieldKind::Gain);
        push(out, WeightKey::BlueFree, eff.blue_tokens as i32, YieldKind::Gain);
        push(out, WeightKey::HandLimit, eff.civil_hand_limit as i32, YieldKind::Gain);
        push(out, WeightKey::HandLimit, eff.military_hand_limit as i32, YieldKind::Gain);
        push(out, WeightKey::ColonizeBonus, eff.colonize_bonus as i32, YieldKind::Gain);
        push(out, WeightKey::ResourceDiscount, eff.resource_discount as i32, YieldKind::Gain);
        push(out, WeightKey::RestrictedResources, eff.resources_for_military_units as i32, YieldKind::Gain);
    }

    // `_BONUS_TO_FEATURE`: the three Military Bonus cards. `defenseBonus` is
    // priced as the INCREMENT over the flat +1 every military card is worth
    // face down (`hand_military` already carries that flat count) --
    // pricing the printed 2/4/6 would double-count the generic discard
    // value. `colonizationBonus` shares `colonize_bonus` with the general
    // `colonizeBonus` key above (`interact.force_value` sums both into the
    // same total, `features()` publishes it once) -- distinct FIELDS
    // (`colonization_bonus` vs `colonize_bonus`) so there is no risk of the
    // two colliding even though they share a target weight.
    if kind == CardType::Bonus {
        push(out, WeightKey::DefenseBonus, eff.defense_bonus as i32 - 1, YieldKind::Bonus);
        push(out, WeightKey::ColonizeBonus, eff.colonization_bonus as i32, YieldKind::Bonus);
    }

    // `_EFF_SPECIAL["wonderStagesPerAction"]`: printed as the TOTAL stages
    // per action (2); one is the base rate every card already has, so the
    // priced amount is the increment.
    if eff.wonder_stages_per_action > 1 {
        push(out, WeightKey::WonderStagesPerAction, eff.wonder_stages_per_action as i32 - 1, YieldKind::Gain);
    }

    for &sp in card.special {
        match sp {
            // `_EFF_SPECIAL["buildDiscount"]`: MAX, not sum -- `buildDiscount`
            // is `{age: resources off}` and a build is of exactly one age,
            // so the ages are ALTERNATIVES. `effects::build_cost` does a
            // single `bd[card.age]` lookup; summing would price a card at
            // something the rules engine never pays out (and get the three
            // Construction techs' relative order wrong: 3:5:6 instead of
            // 1:2:3). `[i16; 5]` is indexed by `Age as u8`, all five slots
            // always present (0 where unprinted), so a plain `max` over the
            // array is exactly Python's `max(bd.values())` over the
            // populated subset -- the unprinted ages are never the max
            // unless every age is 0, in which case there is nothing to gain
            // either way.
            Special::BuildDiscount(ages) => {
                let m = ages.iter().copied().max().unwrap_or(0);
                push(out, WeightKey::BuildDiscount, m as i32, YieldKind::Gain);
            }
            // `_EFF_SPECIAL["freeCivilAction"]`: a presence flag -- WHICH
            // free action it is (18 cards, `FreeCivilActionValue`) does not
            // change what it is worth, only that there is one. `effects.
            // free_civil_action` (the CardEffects field of the same name) is
            // dead for exactly this reason -- see this module's top doc
            // comment -- so this reads the `Special` variant, not the field.
            Special::FreeCivilAction(_) => out.push((WeightKey::FreeCivilAction, 1.0, YieldKind::Gain)),
            _ => {}
        }
    }

    // costs: `techCost`/`buildCost`, `_Y_COST` (clamped to `max(0, w)` by
    // `sum_yields` so a hill-climbed-negative stock weight can never make a
    // cost read as a gain -- see `YieldKind::Cost`'s own doc comment).
    if card.science_cost != 0 {
        out.push((WeightKey::Science, -(card.science_cost as f64), YieldKind::Cost));
    }
    if card.resource_cost != 0 {
        out.push((WeightKey::ResourceStock, -(card.resource_cost as f64), YieldKind::Cost));
    }

    if kind == CardType::Wonder {
        out.push((WeightKey::Wonders, 1.0, YieldKind::Gain));
        if !card.stages.is_empty() {
            let sum: u32 = card.stages.iter().map(|&s| s as u32).sum();
            out.push((WeightKey::ResourceStock, -(sum as f64), YieldKind::Cost));
        }
    }
}

/// `_card_choices`: `name`'s mutually-exclusive alternative, if it has one --
/// `_card_yields` SUMS everything it finds, which is wrong for a card that
/// makes you pick, not take both. Today's only instance is Reserves (I/II/
/// III): "gain N food OR N resources" (`Special::GainFoodOrResources`).
///
/// `Option<(CardYield, CardYield)>`, not a `Vec` of `Vec`s of alternatives:
/// Python's shape is general (a tuple of arbitrary-width groups, each an
/// arbitrary-width tuple of triples) because it is threaded through the same
/// untyped-dict machinery as everything else in the Python module, but there
/// has only ever been ONE choice card shape in the base game since this was
/// written, and DESIGN.md rule 4 says not to allocate a `Vec` for a value
/// this narrow. A future card that printed a three-way choice, or a choice
/// between more than one triple per branch, would need to widen this return
/// type -- which is a compile error at every caller, not a silent width
/// mismatch the way growing Python's tuple-of-tuples would be.
///
/// The caller (valuation layer, not ported here) takes the max of the two
/// branches' [`sum_yields`], e.g. `sum_yields(&[a], w, credit).max(sum_yields
/// (&[b], w, credit))`.
pub fn card_choice(id: CardId) -> Option<(CardYield, CardYield)> {
    id.get().special.iter().find_map(|&sp| match sp {
        Special::GainFoodOrResources(amt) if amt != 0 => Some((
            (WeightKey::FoodStock, amt as f64, YieldKind::Gain),
            (WeightKey::ResourceStock, amt as f64, YieldKind::Gain),
        )),
        _ => None,
    })
}

// --------------------------------------------------------------- sum_yields

/// `_sum_yields`: total eval-points a set of yield triples is worth at
/// weight vector `w`, crediting the short `culture`/`science` RATE spelling
/// at `credit` (`w.get(card_rate_credit)`, resolved ONCE by the caller and
/// threaded through here -- `card_potential` may call this several times per
/// card while pricing board terms, and re-reading the same weight each time
/// would be pure waste).
///
/// Python memoizes the other four credited kinds' weight lookups in a local
/// `dict` within one call, because `w.get(key, default)` there is a
/// `dict.get`. [`Weights::get`](super::weights::Weights::get) is a
/// bounds-checked array index, already as cheap as a memoized read would be,
/// so there is nothing here for a per-call cache to buy back -- reading
/// `w.get(WeightKey::UnitStrengthCredit)` twice in one card's triples (rare:
/// at most one `YieldKind::Unit` triple exists per card today) costs the
/// same as reading it once.
pub fn sum_yields(triples: &[CardYield], w: &Weights, credit: f64) -> f64 {
    let mut total = 0.0;
    for &(key, amount, kind) in triples {
        let mut wk = w.get(key);
        let mut amt = amount;
        match kind {
            YieldKind::Gain => {}
            YieldKind::Cost => {
                if wk < 0.0 {
                    wk = 0.0;
                }
            }
            YieldKind::Rate => amt *= credit,
            YieldKind::Unit => amt *= w.get(WeightKey::UnitStrengthCredit),
            YieldKind::Territory => amt *= w.get(WeightKey::TerritoryCredit),
            YieldKind::Bonus => amt *= w.get(WeightKey::BonusCardCredit),
        }
        if wk != 0.0 && amt != 0.0 {
            total += wk * amt;
        }
    }
    total
}

// -------------------------------------------------- how much board to believe

/// `_BOARD_CREDIT_KEYS`/`_board_credit_key`: the per-type offset on top of
/// `card_board_credit` for a card whose pricing is board-aware
/// ([`board_yields::is_swap_type`] for leader/government/wonder, plus
/// action). `None` for every other type -- there is nothing to offset.
pub fn board_credit_key(id: CardId) -> Option<WeightKey> {
    match id.get().kind {
        CardType::Leader => Some(WeightKey::CardBoardLeader),
        CardType::Government => Some(WeightKey::CardBoardGovernment),
        CardType::Action => Some(WeightKey::CardBoardAction),
        CardType::Wonder => Some(WeightKey::CardBoardWonder),
        _ => None,
    }
}

/// `_swap_type`: `Some(kind)` for a single-slot card (leader/government),
/// else `None`. Deliberately [`board_yields::is_single_slot`], NOT
/// [`board_yields::is_swap_type`]: a wonder is priced by a swap diff too, but
/// two wonders in hand can both be built, so collapsing them the way two
/// leaders (only one of which you can ever hold) collapse would be wrong.
/// See the two predicates' own doc comments in `board_yields.rs`.
pub fn swap_type(id: CardId) -> Option<CardType> {
    let kind = id.get().kind;
    board_yields::is_single_slot(kind).then_some(kind)
}

// ---------------------------------------------- the two ring-fenced yields

/// `_RESTRICTED_TO_FEATURE`: `resource_discount`/`restricted_resources` are
/// not live `evaluate` coordinates (`features()` emits neither), so no game
/// the league plays can put a gradient on them directly. Both are RESOURCES
/// though, so [`yield_marginal`] reroutes them through `resource_stock`'s
/// marginal instead, at a credit that is 1.0 (a discount is worth a whole
/// resource: the build was already going to happen) for the first and a
/// weight (`restricted_resource_credit`, an upper bound a player who builds
/// no units this turn realises none of) for the second. See the Python
/// source's own extensive derivation on `_RESTRICTED_TO_FEATURE`, not
/// reproduced here.
fn restricted_to_feature(key: WeightKey) -> Option<(WeightKey, RestrictedCredit)> {
    match key {
        WeightKey::ResourceDiscount => Some((WeightKey::ResourceStock, RestrictedCredit::Fixed(1.0))),
        WeightKey::RestrictedResources => {
            Some((WeightKey::ResourceStock, RestrictedCredit::Weight(WeightKey::RestrictedResourceCredit)))
        }
        _ => None,
    }
}

/// Whether a ring-fenced feature's credit is the constant `1.0`
/// (`resource_discount`) or itself a weight to look up
/// (`restricted_resource_credit`) -- mirrors Python's `credit` being either a
/// bare `float` or a dict key string, disambiguated there by `isinstance
/// (credit, float)`.
enum RestrictedCredit {
    Fixed(f64),
    Weight(WeightKey),
}

/// `_yield_marginal`: [`rivals::feature_marginal`], plus the two ring-fenced
/// pseudo-features above. `idx: u8`/`late: Option<f64>` match `rivals::
/// feature_marginal`'s own signature exactly (see this module's top doc
/// comment on the `idx` width mismatch with `board_yields.rs`); `ctx` is
/// always `None` here, matching Python's `_yield_marginal(key, state, idx,
/// w, late)` -- it never threads a `RivalContext` through, unlike
/// `strength_marginal`'s other callers.
///
/// Both ring-fenced branches clamp their `feature_marginal` read to
/// `max(0.0, ...)` for the same reason [`YieldKind::Cost`] does: a GAIN
/// (a discount, a ring-fenced resource) must never read as a loss because a
/// hill climb drove `resource_stock` negative.
pub fn yield_marginal(key: WeightKey, state: &GameState, idx: u8, w: &Weights, late: Option<f64>) -> f64 {
    match restricted_to_feature(key) {
        None => rivals::feature_marginal(key, state, idx, w, late, None),
        Some((feat, credit)) => {
            let c = match credit {
                RestrictedCredit::Fixed(v) => v,
                RestrictedCredit::Weight(k) => w.get(k),
            };
            if c == 0.0 {
                0.0
            } else {
                c * rivals::feature_marginal(feat, state, idx, w, late, None).max(0.0)
            }
        }
    }
}

// ---------------------------------------------------- the documented gap

/// `DELIBERATELY_UNPRICED`: every printed effect key `card_yields` does NOT
/// price, with the reason -- mirrors Python's dict of the same name exactly,
/// keyed by the SAME printed JSON key strings (`gainCulturePerLevelOf
/// RemovedCard`, not a Rust identifier), because that is what a future
/// coverage tool (the Rust analogue of `tests/test_card_pricing.py`, not
/// written yet -- see this module's top doc comment on why the type system
/// already closes most of what that test guards) would need to compare
/// against the printed data by.
///
/// This is deliberate design, not dead code: most of what is on a Through
/// the Ages card genuinely cannot be priced by a board-independent per-card
/// table (a tactic's value is a board query; an aggression's loot is capped
/// by what the defender holds; sixteen Age I/II events fire at an
/// unpredictable time against whoever is strongest THEN, not now). The point
/// of naming them here rather than dropping them silently is the same point
/// Python's own comment makes: the SIZE of this list has to stay visible, or
/// a real omission (`culture`/`science` on ten wonders, silent for most of
/// the project's life) hides inside it indistinguishably from a genuine
/// write-off.
///
/// Grouped exactly as the Python source is, one comment per bucket rather
/// than per key -- see `engine/bots/weighted.py` lines 188-436 for the full
/// essay behind each; condensed here to the load-bearing sentence.
pub const DELIBERATELY_UNPRICED: &[(&str, &str)] = &[
    // 1. board-scaled: a numeric coefficient times a board count
    // `card_yields` cannot see, on a card no swap diff reaches (everything
    // else board-scaled moved to `board_yields::BOARD_PRICED`).
    (
        "gainCulturePerLevelOfRemovedCard",
        "board-scaled: coefficient times a board count card_yields cannot see, on a card no swap diff reaches",
    ),
    // 2. text effect: the value is a formula or a bare flag, not a scalar.
    ("doublesTacticBonusOfOneArmy", "text effect: the value is a formula or a bare flag, not a scalar"),
    ("infantryCountsAsCavalryForTactics", "text effect: the value is a formula or a bare flag, not a scalar"),
    // 2a. Bill Gates' end-of-life payout: needs a model of when the leader
    // leaves play.
    (
        "cultureOnLeaveEqualToLabResourceProduction",
        "end-of-life payout: needs a model of when the leader leaves play",
    ),
    // 3. rule change: alters what is legal, not what is produced. All seven
    // that once pointed at an unimplemented rule are implemented now
    // (`actions::_end_politics`/`_leader_politics_moves`/`interact::
    // colonize_without_sacrifice`/etc.) and stay on this list because the
    // reason is now literally true: a rule, not a number to multiply a
    // weight by.
    ("noAttacksBetweenParties", "rule change: alters what is legal, not what is produced"),
    ("cancelledIfPartiesAttackEachOther", "rule change: alters what is legal, not what is produced"),
    ("opponentsPayDoubleMilitaryActionsToAttackYou", "rule change: alters what is legal, not what is produced"),
    ("wonderTakeNoExtraCivilActions", "rule change: alters what is legal, not what is produced"),
    ("revolutionUsesMilitaryActionsInstead", "rule change: alters what is legal, not what is produced"),
    ("oncePerGameTwoPoliticalActions", "rule change: alters what is legal, not what is produced"),
    ("removeAsPoliticalActionForYellowToken", "rule change: alters what is legal, not what is produced"),
    ("removeAsPoliticalActionFreeColonize", "rule change: alters what is legal, not what is produced"),
    ("peekTopEventCardInPolitics", "rule change: alters what is legal, not what is produced"),
    ("militaryActionCombinedPopIncreaseAndUnitBuild", "rule change: alters what is legal, not what is produced"),
    ("civilActionUpgradeUrbanBuildingToTheater", "rule change: alters what is legal, not what is produced"),
    ("militaryActionAsCivilPerTurn", "rule change: alters what is legal, not what is produced"),
    ("civilActionBackOnTechDevelop", "rule change: alters what is legal, not what is produced"),
    ("colonizeDiscardUpTo2MilitaryCardsForBonus", "rule change: alters what is legal, not what is produced"),
    ("colonyPermanentBonusTransfers", "rule change: alters what is legal, not what is produced"),
    ("colonyImmediateBonusApplies", "rule change: alters what is legal, not what is produced"),
    (
        "orTakesSpecialTechnologiesOfSameTotalScienceCost",
        "rule change: alters what is legal, not what is produced",
    ),
    ("removeFromGame", "rule change: alters what is legal, not what is produced"),
    ("onReplacePutUnderCompletedWonderHappy", "rule change: alters what is legal, not what is produced"),
    ("libraryDiscountsIfTheater", "rule change: alters what is legal, not what is produced"),
    // 4. trigger: pays per future event, not on play; needs a measured
    // firing rate, not a guessed one.
    ("scienceOnTechCardTake", "trigger: pays per future event, not on play; needs a measured firing rate"),
    ("resourceOnTechDevelop", "trigger: pays per future event, not on play; needs a measured firing rate"),
    ("cultureOnTechDevelop", "trigger: pays per future event, not on play; needs a measured firing rate"),
    (
        "resourceOnMilitaryUnitBuildOrUpgrade",
        "trigger: pays per future event, not on play; needs a measured firing rate",
    ),
    ("cultureOnRevolution", "trigger: pays per future event, not on play; needs a measured firing rate"),
    ("leaderTakeCivilActionDiscount", "trigger: pays per future event, not on play; needs a measured firing rate"),
    ("comboFoodDiscount", "trigger: pays per future event, not on play; needs a measured firing rate"),
    ("comboResourceDiscount", "trigger: pays per future event, not on play; needs a measured firing rate"),
    ("theaterTechScienceDiscount", "trigger: pays per future event, not on play; needs a measured firing rate"),
    ("theaterResourceDiscountIfLibrary", "trigger: pays per future event, not on play; needs a measured firing rate"),
    ("theaterScienceDiscountIfLibrary", "trigger: pays per future event, not on play; needs a measured firing rate"),
    // 5. tactic bonus: board-scaled, and a duplicate spelling of the
    // top-level strength `card_yields` already prices through `YieldKind::
    // Unit`/the flat-strength branch for every OTHER type -- see this
    // module's top doc comment and `tactic_outlook`.
    (
        "tacticBonus",
        "tactic bonus: board-scaled, and a duplicate spelling of the top-level strength the engine reads",
    ),
    (
        "tacticBonusObsolete",
        "tactic bonus: board-scaled, and a duplicate spelling of the top-level strength the engine reads",
    ),
    // 5a. aggression/war payoffs: priced by RESOLUTION (quiescence plays the
    // defense out; `quiescent.war_value` calls the engine's own
    // `resolve_war`), not by a table -- a table entry would double count
    // against a resolution that has already happened.
    ("destroyUrbanBuildings", "priced by resolution, not by table: quiescence plays the defense out"),
    ("opponentDecreasesPopulation", "priced by resolution, not by table: quiescence plays the defense out"),
    ("stealColony", "priced by resolution, not by table: quiescence plays the defense out"),
    ("takeFromOpponent", "priced by resolution, not by table: quiescence plays the defense out"),
    ("victorTakesYellowTokens", "priced by resolution, not by table: quiescence plays the defense out"),
    ("victorTakesScienceUpTo", "priced by resolution, not by table: quiescence plays the defense out"),
    ("victorTakesCulture", "priced by resolution, not by table: quiescence plays the defense out"),
    ("decreasePopulation", "priced by resolution, not by table: quiescence plays the defense out"),
    // 6. event/pact structure: nested "who it happens to" blocks. Events are
    // resolved by the rules engine; pacts are priced through
    // `deferred_credit`, which reads INSIDE these blocks. The 15 Age III
    // "Impact of ..." events are priced separately, board-aware, through
    // `event_scoring_margin`; the 16 rank-addressed Age I/II events are left
    // unpriced deliberately (they fire at an unpredictable time against
    // whoever is strongest/weakest THEN, and their printed swings are small).
    ("allPlayers", "addressing: names who an event or pact side applies to, not a yield"),
    ("bothPlayers", "addressing: names who an event or pact side applies to, not a yield"),
    ("weakestPlayer", "addressing: names who an event or pact side applies to, not a yield"),
    ("weakestPlayers", "addressing: names who an event or pact side applies to, not a yield"),
    ("strongestPlayer", "addressing: names who an event or pact side applies to, not a yield"),
    ("strongestPlayers", "addressing: names who an event or pact side applies to, not a yield"),
    ("playerWithMostCulture", "addressing: names who an event or pact side applies to, not a yield"),
    ("playerWithLeastCulture", "addressing: names who an event or pact side applies to, not a yield"),
    ("playersWithMostHappyFaces", "addressing: names who an event or pact side applies to, not a yield"),
    ("playersWithMostDiscontentWorkers", "addressing: names who an event or pact side applies to, not a yield"),
    ("target", "addressing: names who an event or pact side applies to, not a yield"),
    ("condition", "addressing: names who an event or pact side applies to, not a yield"),
    ("duration", "addressing: names who an event or pact side applies to, not a yield"),
    ("lastRoundSubstitute", "addressing: names who an event or pact side applies to, not a yield"),
    ("onAttackBetweenParties", "addressing: names who an event or pact side applies to, not a yield"),
    ("gain", "addressing: names who an event or pact side applies to, not a yield"),
    ("lose", "addressing: names who an event or pact side applies to, not a yield"),
    ("A", "addressing: names who an event or pact side applies to, not a yield"),
    ("B", "addressing: names who an event or pact side applies to, not a yield"),
    // 7. prose.
    ("note", "prose: a rules clarification for human readers"),
];

/// `UNPRICED_VALUES`: the gap one level down from [`DELIBERATELY_UNPRICED`] --
/// keyed by (card name, effect key), for a key that IS mapped but whose
/// value on THIS card is prose rather than a number (`gainResources` is
/// numeric on most cards and a sentence on the three Raids). `gen_cards.py`
/// already resolves this class structurally on the Rust side: a card whose
/// value is prose gets a [`Special`] variant instead of a numeric
/// `CardEffects` field (see this module's top doc comment), so
/// `CardEffects.gain_resources` is simply `0` on all three Raids and
/// [`card_yields`] never sees a number to misprice -- this table exists for
/// the same audit-trail reason [`DELIBERATELY_UNPRICED`] does (SIZE visible,
/// not dropped silently), not because Rust needs it to behave correctly.
pub const UNPRICED_VALUES: &[(&str, &str, &str)] = &[
    (
        "Aggression: Raid (I)",
        "gainResources",
        "prose amount: half of each destroyed building's cost, chosen at resolution, not a card property",
    ),
    (
        "Aggression: Raid (II)",
        "gainResources",
        "prose amount: half of each destroyed building's cost, chosen at resolution, not a card property",
    ),
    (
        "Aggression: Raid (III)",
        "gainResources",
        "prose amount: half of each destroyed building's cost, chosen at resolution, not a card property",
    ),
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cards::CardId;

    fn yields_of(name: &str) -> Vec<CardYield> {
        let mut out = Vec::new();
        card_yields(CardId::by_name(name).unwrap_or_else(|| panic!("no such card: {name}")), &mut out);
        out
    }

    fn amount_of(name: &str, key: WeightKey) -> f64 {
        yields_of(name).into_iter().filter(|&(k, _, _)| k == key).map(|(_, a, _)| a).sum()
    }

    /// The headline fix docs/CARD_BLINDNESS.md exists to describe: Eiffel
    /// Tower's short-spelling `culture` reads as `culture_rate`, not as
    /// nothing.
    #[test]
    fn eiffel_tower_culture_is_priced_as_culture_rate() {
        assert_eq!(amount_of("Eiffel Tower", WeightKey::CultureRate), 4.0);
    }

    /// `buildDiscount` is a MAX over ages, not a sum -- Masonry prints
    /// `{I:1, II:1, III:1}`, which is 1, not 3.
    #[test]
    fn masonry_build_discount_is_the_max_not_the_sum() {
        assert_eq!(amount_of("Masonry", WeightKey::BuildDiscount), 1.0);
        assert_eq!(amount_of("Masonry", WeightKey::WonderStagesPerAction), 1.0);
    }

    #[test]
    fn architecture_build_discount_is_two_not_five() {
        assert_eq!(amount_of("Architecture", WeightKey::BuildDiscount), 2.0);
    }

    /// A unit's per-worker strength prices as `YieldKind::Unit`, not as a
    /// pure cost -- the ten-unit-cards-strictly-negative bug this file's top
    /// doc comment describes.
    #[test]
    fn warriors_strength_is_a_unit_yield() {
        let ys = yields_of("Warriors");
        assert!(ys.contains(&(WeightKey::Strength, 1.0, YieldKind::Unit)), "{ys:?}");
        assert!(ys.contains(&(WeightKey::ResourceStock, -2.0, YieldKind::Cost)), "{ys:?}");
    }

    /// A tactic's top-level `strength` (its army bonus, fused into the same
    /// field a unit's per-worker strength uses) must never surface as a
    /// yield at all -- DELIBERATELY_UNPRICED bucket 5.
    #[test]
    fn a_tactic_never_prices_its_own_strength() {
        let ys = yields_of("Heavy Cavalry");
        assert!(!ys.iter().any(|&(k, _, _)| k == WeightKey::Strength), "{ys:?}");
    }

    /// A government's top-level action counts (fused into the same fields a
    /// genuine `effects.civilActions`/`militaryActions` grant uses) must
    /// never surface as a card yield -- Python's `_card_yields` never reads
    /// them either (`gov_value`'s board-aware job, not this file's).
    #[test]
    fn a_government_never_prices_its_own_action_counts() {
        let ys = yields_of("Despotism");
        assert!(!ys.iter().any(|&(k, _, _)| k == WeightKey::CivilActions || k == WeightKey::MilitaryActions), "{ys:?}");
    }

    /// A territory's flat numbers price through `YieldKind::Territory`, not
    /// as a bare gain -- and its `happy`/`happiness` substitutes to
    /// `happy_margin`, matching the general-effects path exactly.
    #[test]
    fn a_territory_prices_through_the_territory_kind() {
        let ys = yields_of("Historic Territory (I)");
        assert!(ys.contains(&(WeightKey::HappyMargin, 1.0, YieldKind::Territory)), "{ys:?}");
        assert!(ys.contains(&(WeightKey::Culture, 6.0, YieldKind::Territory)), "{ys:?}");
        // never double-counted as a bare gain alongside the credited triple
        assert!(!ys.contains(&(WeightKey::HappyMargin, 1.0, YieldKind::Gain)), "{ys:?}");
    }

    /// The three Military Bonus cards: defence is the INCREMENT over the
    /// flat +1 every military card already carries.
    #[test]
    fn bonus_card_defense_is_priced_as_the_increment() {
        assert_eq!(amount_of("Military Bonus (defense 2 / colonization 1)", WeightKey::DefenseBonus), 1.0);
        assert_eq!(amount_of("Military Bonus (defense 4 / colonization 2)", WeightKey::DefenseBonus), 3.0);
        assert_eq!(amount_of("Military Bonus (defense 2 / colonization 1)", WeightKey::ColonizeBonus), 1.0);
    }

    /// Reserves is a choice, not a sum -- `card_yields` alone must not price
    /// both branches (that would be pricing 4 food AND 4 resources for a
    /// card that grants one or the other).
    #[test]
    fn reserves_has_no_card_yields_entry_of_its_own() {
        let ys = yields_of("Reserves (I)");
        assert!(ys.is_empty(), "{ys:?}");
        let choice = card_choice(CardId::by_name("Reserves (I)").unwrap());
        assert_eq!(
            choice,
            Some((
                (WeightKey::FoodStock, 2.0, YieldKind::Gain),
                (WeightKey::ResourceStock, 2.0, YieldKind::Gain)
            ))
        );
    }

    #[test]
    fn wonders_pay_a_stage_cost_and_grant_a_wonders_point() {
        let ys = yields_of("Colossus");
        assert!(ys.contains(&(WeightKey::Wonders, 1.0, YieldKind::Gain)), "{ys:?}");
        assert!(ys.iter().any(|&(k, a, kd)| k == WeightKey::ResourceStock && a < 0.0 && kd == YieldKind::Cost), "{ys:?}");
    }

    // ------------------------------------------------------------ sum_yields

    #[test]
    fn sum_yields_clamps_a_negative_cost_weight_to_zero() {
        let mut w = Weights::default();
        w.set(WeightKey::Science, -1.0);
        let triples = [(WeightKey::Science, -4.0, YieldKind::Cost)];
        // a negative weight on a COST triple must price as 0.0, never as a
        // gain (-1.0 * -4.0 = 4.0 would be exactly the "cost reads as a
        // bargain" bug this kind exists to prevent).
        assert_eq!(sum_yields(&triples, &w, 1.0), 0.0);
    }

    #[test]
    fn sum_yields_gates_the_rate_kind_on_the_credit_argument() {
        let mut w = Weights::default();
        w.set(WeightKey::CultureRate, 2.0);
        let triples = [(WeightKey::CultureRate, 4.0, YieldKind::Rate)];
        assert_eq!(sum_yields(&triples, &w, 1.0), 8.0);
        assert_eq!(sum_yields(&triples, &w, 0.0), 0.0);
    }

    #[test]
    fn sum_yields_scales_each_credited_kind_by_its_own_weight() {
        let mut w = Weights::default();
        w.set(WeightKey::Strength, 1.0);
        w.set(WeightKey::UnitStrengthCredit, 0.5);
        w.set(WeightKey::TerritoryCredit, 2.0);
        w.set(WeightKey::BonusCardCredit, 3.0);
        assert_eq!(sum_yields(&[(WeightKey::Strength, 4.0, YieldKind::Unit)], &w, 1.0), 2.0);
        assert_eq!(sum_yields(&[(WeightKey::Strength, 4.0, YieldKind::Territory)], &w, 1.0), 8.0);
        assert_eq!(sum_yields(&[(WeightKey::Strength, 4.0, YieldKind::Bonus)], &w, 1.0), 12.0);
    }

    // ------------------------------------------------------- board plumbing

    #[test]
    fn board_credit_key_covers_exactly_the_four_board_priced_types() {
        assert_eq!(board_credit_key(CardId::by_name("Julius Caesar").unwrap()), Some(WeightKey::CardBoardLeader));
        assert_eq!(board_credit_key(CardId::by_name("Despotism").unwrap()), Some(WeightKey::CardBoardGovernment));
        assert_eq!(board_credit_key(CardId::by_name("Reserves (I)").unwrap()), Some(WeightKey::CardBoardAction));
        assert_eq!(board_credit_key(CardId::by_name("Colossus").unwrap()), Some(WeightKey::CardBoardWonder));
        assert_eq!(board_credit_key(CardId::by_name("Warriors").unwrap()), None);
    }

    #[test]
    fn swap_type_is_single_slot_only_not_every_swap_type() {
        assert_eq!(swap_type(CardId::by_name("Julius Caesar").unwrap()), Some(CardType::Leader));
        assert_eq!(swap_type(CardId::by_name("Despotism").unwrap()), Some(CardType::Government));
        // a wonder IS a swap-diff type but NOT single-slot: two in hand are
        // two independent candidates, not one replacement.
        assert_eq!(swap_type(CardId::by_name("Colossus").unwrap()), None);
    }

    // -------------------------------------------------------- yield_marginal
    //
    // `rivals::feature_marginal` is real (landed while this file was being
    // written -- see this module's top doc comment), so these exercise the
    // actual dependency rather than a mock. `ResourceStock` is neither a
    // `PHASE_KEYS` nor a `RATE_KEYS` member (`horizon.rs`'s own lists), so
    // `feature_marginal(ResourceStock, ...)` is exactly `w.get(ResourceStock)`
    // with no board dependency at all -- which is what makes it possible to
    // pin the two ring-fenced branches' arithmetic without needing a
    // particular board shape.

    #[test]
    fn yield_marginal_passes_through_an_ordinary_key_untouched() {
        let state = crate::game::new_game(2, 1);
        let mut w = Weights::default();
        // an ordinary (non-ring-fenced) key must equal calling
        // `rivals::feature_marginal` directly -- `yield_marginal` adds
        // nothing for it.
        w.set(WeightKey::RateHorizon, 0.0); // pin `culture_rate`'s horizon scaling at 1.0
        let direct = rivals::feature_marginal(WeightKey::CultureRate, &state, 0, &w, None, None);
        assert_eq!(yield_marginal(WeightKey::CultureRate, &state, 0, &w, None), direct);
    }

    #[test]
    fn yield_marginal_reroutes_resource_discount_through_resource_stock_at_credit_one() {
        let state = crate::game::new_game(2, 1);
        let mut w = Weights::default();
        w.set(WeightKey::ResourceStock, 3.0);
        // credit is the fixed constant 1.0 -- the whole `resource_stock`
        // marginal passes through unscaled.
        assert_eq!(yield_marginal(WeightKey::ResourceDiscount, &state, 0, &w, None), 3.0);
    }

    #[test]
    fn yield_marginal_gates_restricted_resources_on_its_own_credit_weight() {
        let state = crate::game::new_game(2, 1);
        let mut w = Weights::default();
        w.set(WeightKey::ResourceStock, 8.0);
        w.set(WeightKey::RestrictedResourceCredit, 0.0);
        assert_eq!(yield_marginal(WeightKey::RestrictedResources, &state, 0, &w, None), 0.0);

        w.set(WeightKey::RestrictedResourceCredit, 0.25);
        assert_eq!(yield_marginal(WeightKey::RestrictedResources, &state, 0, &w, None), 2.0);
    }

    #[test]
    fn yield_marginal_clamps_a_negative_marginal_to_zero_for_both_ring_fenced_keys() {
        let state = crate::game::new_game(2, 1);
        let mut w = Weights::default();
        w.set(WeightKey::ResourceStock, -5.0);
        assert_eq!(yield_marginal(WeightKey::ResourceDiscount, &state, 0, &w, None), 0.0);
        w.set(WeightKey::RestrictedResourceCredit, 1.0);
        assert_eq!(yield_marginal(WeightKey::RestrictedResources, &state, 0, &w, None), 0.0);
    }

    // --------------------------------------------------------- CardType

    #[test]
    fn is_action_and_is_government_match_the_type_they_name() {
        assert!(CardId::by_name("Reserves (I)").unwrap().kind().is_action());
        assert!(!CardId::by_name("Despotism").unwrap().kind().is_action());
        assert!(CardId::by_name("Despotism").unwrap().kind().is_government());
        assert!(!CardId::by_name("Reserves (I)").unwrap().kind().is_government());
    }

    // ------------------------------------------------- documented registries

    #[test]
    fn deliberately_unpriced_has_no_duplicate_keys() {
        let mut keys: Vec<&str> = DELIBERATELY_UNPRICED.iter().map(|&(k, _)| k).collect();
        let before = keys.len();
        keys.sort_unstable();
        keys.dedup();
        assert_eq!(keys.len(), before, "a key listed more than once");
    }

    #[test]
    fn unpriced_values_has_no_duplicate_pairs() {
        let mut pairs: Vec<(&str, &str)> = UNPRICED_VALUES.iter().map(|&(n, k, _)| (n, k)).collect();
        let before = pairs.len();
        pairs.sort_unstable();
        pairs.dedup();
        assert_eq!(pairs.len(), before, "a (card, key) pair listed more than once");
    }

    #[test]
    fn every_reason_is_a_real_sentence_not_a_stub() {
        for &(k, why) in DELIBERATELY_UNPRICED {
            assert!(why.len() > 20, "{k}: reason too short to be real: {why:?}");
        }
        for &(n, k, why) in UNPRICED_VALUES {
            assert!(why.len() > 20, "{n}/{k}: reason too short to be real: {why:?}");
        }
    }
}
